### ISSUE TITLE
ObsoleteURI check needs to provide more help (or documentation)

### ISSUE THREAD

**Issue by kentfredric** [pkgcore/pkgcheck#114]
Especially with the github URI's, moving from one to the other causes a checksum to change, which introduces fun problems if the old version is cached on distfiles.gentoo.org:

- Maintainer-nuking `Manifest` and `/usr/portage/distfiles` and running `repoman manifest` gives you a wrong `Manifest` entry if the user fetches directly from the URL mentioned in `SRC_URI` (due to default mechanics being to simply refetech from `distfiles.gentoo.org`)
- running `repoman manifest` with `GENTOO_MIRRORS="" repoman manifest` gets you the right checksums, but at the expense that users will still fetch from the `distfiles.gentoo.org` mirror, and get wrong checksummed files
- In some cases, this specific URI might suggest maintainers look and see if upstream have a `/releases/` page, and consider using those results instead, however, doing so is still subject to the original two problems above.
- Adding a suffix in `SRC_URI` like ` -> ${P}.gh2.tar.gz` will satisfy the aforementioned checksum issues, but will now create a problem in `src_prepare` due to the tarball being extracted as `${WORKDIR}/${P}.gh2` and `src_prepare` will try to  access `${WORKDIR}/${P}` which doesn't exist, so you *also* need to make sure you do `S="${WORKDIR}/${P}.gh2"`

In the case above of "migrate from `/tarball/` to `/releases/` instead of `/archive/`, I humbly  suggest using the suffix `.original.tar.gz` ( as its the original sources provided by upstream, not some mess of github rolling a tar from a SHA1 with risks of random checksum changes )

I suggest some documentation be at least, placed here: https://pkgcheck.readthedocs.io/en/latest/man/pkgcheck.html#obsoleteuri , but some mention of some kind of pitfall aught to be mentioned in the warning itself.

Enhancing the error in any way that leads developers to the best conclusion is greatly desired, especially as this is the sort of situation where somebody could think "Oh, easy fix", test it, find no bugs, and only later work it out after much confusion from a cryptic user bug report.

( I would hope, for a minimum effort approach, maintainers might see this bug before trusting `repoman commit` to make sure this mess doesn't happen... )

**Comment by mgorny** [comment]
> Adding a suffix in SRC_URI like -> ${P}.gh2.tar.gz will satisfy the aforementioned checksum issues, but will now create a problem in src_prepare due to the tarball being extracted as ${WORKDIR}/${P}.gh2 and src_prepare will try to access ${WORKDIR}/${P} which doesn't exist, so you also need to make sure you do S="${WORKDIR}/${P}.gh2"

It shouldn't, as replacement kills the need for vcs-snapshot.

**Comment by radhermit** [comment]
Optimally, I'd prefer if ``repoman manifest`` handled all this internally and I'll probably make its analog ``pmaint digest`` do that without having to do anything other than updating SRC_URI. The fetching process should fallback to pulling from upstream directly if the files from gentoo mirrors don't match the checksum.

In the meantime I guess we can recommend renaming things.
