### ISSUE TITLE
Implement package.deprecated

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#127]
See https://archives.gentoo.org/gentoo-dev/message/3150098d9f4e3a698110cb76ae28d1d9

Basically, `package.deprecated` that works just like `package.mask`, except that instead of user-visible masking it causes pkgcheck to report warnings. The best way would probably be to apply it on top of current dependency checks.

**Comment by radhermit** [comment]
Would you foresee profile specific package.deprecated files or just a single file/dir of files in the profiles base dir?

**Comment by radhermit** [comment]
Basically if you allow profile specific stuff then this needs to be implemented in the visibility check which iterates over profiles (along with support for collapsing across parents in pkgcore profile code). However, if it's not profile specific it can go in the standard dependency check as it's just matching a restriction against each dep.

**Comment by mgorny** [comment]
> Would you foresee profile specific package.deprecated files or just a single file/dir of files in the profiles base dir?

Nope, just single list. However, I do expect to have `|| ( a b )` deps where only one of those packages is deprecated, and I'm not sure if we want to report this if the other (non-deprecated) branch is visible.

**Comment by radhermit** [comment]
Do you have an example for any-of group usage? Adding depset syntax to non-ebuild files starts seeming like unnecessary complexity.

**Comment by mgorny** [comment]
I meant any-of in tested package, i.e. package has `|| ( a b )`, and package.deprecated lists `a` but `b` is fine.

**Comment by radhermit** [comment]
Oh, that's already handled in the dep checker iirc so it shouldn't be a problem.

**Comment by mgorny** [comment]
I think handling that correctly with regards to visibility requires integrating it in the per-profile loop anyway.

**Comment by mgorny** [comment]
Actually, thinking about it we'd probably want two classes of warnings for this: one for dependencies that can't be satisfied by other any-of branches, and another for dependencies that can.

The basic idea is that if we move an entry from `package.deprecated` to `package.mask`, the first class would turn into `NonexistentDeps` while the other would turn into `NonsolvableDeps*`. In other words, fixing the second group would be necessary prior to masking the package but not the first.

**Comment by radhermit** [comment]
Now that I have this pretty much implemented I'm not entirely convinced we need two separate classes for optional and non-optional dep types. Are you worried about excessive, unnecessary churn by flagging deprecated ``|| ( a b )`` deps for removal?

Also, I don't see the point in implementing this in a profile-related fashion since both the base package.mask and package.deprecated files are applied in this context without any knowledge of profiles. Additional profile files affecting visibility aren't applicable here, unless we want to allow profile-specific package.deprecated or something similar.

**Comment by mgorny** [comment]
Both points were relevant to `|| ( a b )` deps. I suppose for now it's sufficient to just flag any occurence of package.
