### ISSUE TITLE
git support not working

### ISSUE THREAD

**Issue by sbraz** [pkgcore/pkgcheck#129]
Hi @radhermit,
As discussed on IRC, here is my config:
```ini
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "sbraz"]
        url = git@github.com:sbraz/gentoo.git
        fetch = +refs/heads/*:refs/remotes/sbraz/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[remote "upstream"]
      url = https://github.com/gentoo/gentoo
      fetch = +refs/heads/*:refs/remotes/upstream/*

[gitg]
        mainline = refs/heads/master
[gui]
        wmstate = normal
        geometry = 1598x850+0+19 192 177
[remote "history"]
        url = https://github.com/gentoo/gentoo-gitmig-20150809-draft.git
        fetch = +refs/heads/*:refs/remotes/history/*
[push]
        gpgSign = if-asked
[user]
        email = sbraz@gentoo.org
[remote "origin"]
        url = https://anongit.gentoo.org/git/repo/gentoo.git
        fetch = +refs/heads/*:refs/remotes/origin/*
        pushurl = git+ssh://git@git.gentoo.org/repo/gentoo.git
[pull]
        rebase = 1
[remote "githubgentoo"]
        url = git@github.com:gentoo/gentoo.git
        fetch = +refs/heads/*:refs/remotes/githubgentoo/*
```
And the output of `pkgcheck scan -k OutdatedBlocker --debug` from the root of the repo:
```
Running 1 tests  
```
Then it hangs

**Comment by radhermit** [comment]
I followed the method of grafting the git history onto an entirely new repo clone described at https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Grafting_Gentoo_history_onto_the_active_repository and everything works fine for me with the following git config:

```
[core]
        repositoryformatversion = 0
        filemode = true
        bare = false
        logallrefupdates = true
[remote "origin"]
        url = git+ssh://git@git.gentoo.org/repo/gentoo.git
        fetch = +refs/heads/*:refs/remotes/origin/*
[branch "master"]
        remote = origin
        merge = refs/heads/master
[remote "history"]
        url = https://github.com/gentoo/gentoo-gitmig-20150809-draft.git
        fetch = +refs/heads/*:refs/remotes/history/*
```

Anyway, I've added some progressive output when building git caches under debug mode to the git repo, so I'll ping this issue again for you to test when that makes it into the next release.

**Comment by radhermit** [comment]
Try running the same command with 0.6.3 now. It should show progressive output as it scans the git log.

**Comment by sbraz** [comment]
It's now failing with "failed retrieving origin/HEAD commit hash for git repo".
I ran `git remote set-head origin master` and it seems to work now :) It's scanning a bunch of commits.

**Comment by radhermit** [comment]
Yep looks good. Before what was happening was the check was running anyway but skipping that related git part because the cached repo was null. So no output was produced because that command filters all outputted keywords for the git related OutdatedBlocker specifically which would never get thrown when the cached repo doesn't exist.

Once I add a cache addon to generically handle cache registry/updates it should be easier to exit in this case. In the meantime, I'm closing this since it isn't a bug but an unsupported config and I'll open a bug about adding supported  git config info the the man page.
