### ISSUE TITLE
BadInsIntoCheck could check for /usr/share/doc/${PF}

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#135]
Suggested by @SoapGentoo. In new enough EAPIs, it can (and probably should) be replaced with `dodoc`/`docinto`.

**Comment by SoapGentoo** [comment]
yes please, I'm seeing what too many `insinto /usr/share/doc/${PF}` calls all over the place

**Comment by radhermit** [comment]
Do we also want to flag usage of ``insinto /usr/share/doc/${P}`` when ``${PF}`` should be used instead?

**Comment by radhermit** [comment]
For older EAPIs I meant, or do we not care about such things since they should port away from that anyway when updating.

**Comment by SoapGentoo** [comment]
Yes, I would think so.

**Comment by SoapGentoo** [comment]
@radhermit will your check also catch `insinto /usr/share/doc/${P}` (which is not that uncommon)?

**Comment by radhermit** [comment]
It'll catch it for newer EAPIs same as the ${PF} variant.

**Comment by SoapGentoo** [comment]
oh I missed the `?`, never mind
