### ISSUE TITLE
Add support for ignoring directories (eg metadata, distfiles)

### ISSUE THREAD

**Issue by perfinion** [pkgcore/pkgcheck#140]
I have my portage tree in `/usr/portage` and use post-sync hooks to update the metadata. The main gentoo package has .gitignore entries to ignore `/metadata` and `/distfiles` and `/packages` and things like that so I can develop and also keep portage happy. 

When I run `pkgcheck scan` in the base of the tree, I get lots of entries complaining about binary files found in repository, some examples:

```
BinaryFile: binary file found in repository: 'distfiles/git3-src/zfsonlinux_zfs.git/objects/fd/0d23502a43c877cc1b8a0bf326f92d07290c75'
BinaryFile: binary file found in repository: 'distfiles/LVM2.2.02.173.tgz'
BinaryFile: binary file found in repository: 'metadata/md5-cache/Manifest.gz'
BinaryFile: binary file found in repository: 'metadata/news/.git/objects/cd/6e676cb18e3380ac7b8649bab2a1f636c630bd'
```

Can there be some way to make pkgcheck ignore entire dirs? It could either use the `.gitignore` or I could write them in the pkgcheck config.

**Comment by radhermit** [comment]
Is there a reason you can't move to the newer layout where distfiles and packages aren't subdirs of the gentoo repo? That would drop some of the reports at least.
