### ISSUE TITLE
Add an option to limit some checks to newest non-vcs version

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#144]
Right now we get a lot of reports about `Deprecated*` and like that for old versions where the issue has been fixed in newer version. I suppose it'd be valuable to have an option that would filter those checks only to newest non-VCS + VCS versions in every slot. Probably should involve adding some boolean property to checks, to indicate whether it's interesting for old versions.

**Comment by radhermit** [comment]
This could probably be done with a custom source that yields the requested, filtered pkg set instead of all matches.

**Comment by mgorny** [comment]
Yeah, just note that this actually needs to be done only for some checks. For example, `RedundantVersion` makes sense only for old versions ;-).

**Comment by radhermit** [comment]
It would help to enumerate which checks you'd want this for even if I can guess perhaps 90% of the list.

I'd probably make this hinge on -v/--verbose meaning the filtered source would be used by default, but all results would still show up under verbose mode.

**Comment by radhermit** [comment]
Note that you'll now need to enumerate which checks you want limited to the latest pkgs as I have only enabled the network checks to use the filter so far.

The main caveat remaining is that the support currently doesn't handle checks that will yield both filtered and unfiltered results. To do that, attrs will probably need to be injected into the pkg objects that are then checked during result obj instantiation.

**Comment by mgorny** [comment]
Lemme see. My initial list would be:

```
AbsoluteSymlinkCheck
BadInsIntoCheck
ConditionalTestRestrictCheck
DeprecatedEclassCheck
DescriptionCheck
HomepageInSrcUriCheck
HttpsAvailableCheck
MissingSlotDepCheck
MissingUnpackerDepCheck
ObsoleteUriCheck
PortageInternalsCheck
PythonCheck
WhitespaceCheck
```

Those need to be split more, as some results are relevant to newest version, and some to all versions:
```
MetadataCheck
PathVariablesCheck
RequiredUSEMetadataCheck
SrcUriCheck
```
