### ISSUE TITLE
Check for forbidden functions in various EAPI's

### ISSUE THREAD

**Issue by kentfredric** [pkgcore/pkgcheck#148]
It would be nice if violations like people using (banned) dohtml in EAPI7.

Its otherwise too easy to look at a package and think "oh, so I'm just here to fix a dep, lets EAPI7-ify-it while were here", and be misguided into thinking that doing so is effectively free, and that you probably don't need to test the ebuild for such a trivial change,... like what I expect happend here: 
- https://bugs.gentoo.org/688886
- https://bugs.gentoo.org/694958

Seems to me this class of problems could plausibly be defended against, or at least, have QA reports cry about.

**Comment by radhermit** [comment]
Similar to #50, I was putting this off until I have some reasonably sane bash parser working. I guess we could see how many false positives some crazy regex would produce in the meantime if someone wants to add support sooner.

**Comment by radhermit** [comment]
A hacky regex solution doesn't seem to cause to many too false positives so it's now available via DeprecatedEapiCommand and BannedEapiCommand results.
