### ISSUE TITLE
network checks: report 301 redirects (only)

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#149]
I've looked into the network check code, and I have two suggestions:

1. `FetchablesUrlCheck` should also report redirects,
2. Both checks should report *only* 301 (permanent) redirects. Reporting 302 is simply incorrect.

**Comment by radhermit** [comment]
I was waiting to do this until I ported it to use the requests library instead of urllib since it's much easier to do using that.

**Comment by radhermit** [comment]
Unfortunately requests doesn't support ftp:// links though so urllib support will probably have to stick around anyway for that.
