### ISSUE TITLE
MissingLicenseRestricts flags packages with no sources as missing RESTRICT=mirror

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#150]
E.g. `games-action/fakk2`. I suppose adding `RESTRICT=mirror` to an ebuild with no `SRC_URI` makes no sense, so we should skip such ebuilds in the check.

Sadly, this also means we're going to flag ebuilds that get sources elsewhere (`cdrom.eclass`) and carry patches in `SRC_URI`. Maybe we should have a property for this kind of ebuilds.

**Comment by mgorny** [comment]
Hm, maybe using `PROPERTIES=interactive` would be good enough.

**Comment by mgorny** [comment]
Or even better (with @ulm's blessing): checking for `cdrom` in inherits.

**Comment by radhermit** [comment]
So skip flagging if SRC_URI is empty or it inherits the cdrom eclass? What about if cdrom support is optional, i.e. it sets ``CDROM_OPTIONAL="yes"``?

**Comment by radhermit** [comment]
Honestly I'd rather just skip empty SRC_URIs and ignore the cdrom eclass with patches case as cdrom usage should be limited and dying off anyway.

**Comment by radhermit** [comment]
Skipping empty SRC_URI fixed in 621ecf9dec823e32e00ae821eaf2ee6a9b5479fa. Feel free to open another issue down the road if significant false positives remain for varied cdrom usage after the valid issues are fixed.
