### ISSUE TITLE
pkgcheck tries to scan wrong repo while expected to work in cwd

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#164]
```
$ cd ~/git/gentoo
$ pkgcheck scan --net --git-disable  $(git diff origin --name-only $(<profiles/categories) | cut -d/ -f1-2 | sort -u)
pkgcheck scan: error: 'mgorny' repo doesn't contain: 'dev-lang/python'
```

Except that `mgorny` is not the right repo, and I really have no clue how it could come to that conclusion. cwd is not in repos.conf, and `gentoo` is set as default repo there.

**Comment by radhermit** [comment]
Pretty sure this is fixed by https://github.com/pkgcore/pkgcheck/commit/d758cd460f3a7463bfb0f83fe73b35faac1d3a56.
