### ISSUE TITLE
Add network checks for metadata.xml entries

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#167]
The `<upstream/>` section contains some possibly-URLs that we could check:
* changelog,
* doc
* bugs-to
* remote-id

https://www.gentoo.org/glep/glep-0068.html#upstream-descriptions

**Comment by radhermit** [comment]
Is there a mapping somewhere for remote-id values to base service URLs?

**Comment by mgorny** [comment]
No, I don't think so. In fact, you might be the first consumer of them ;-).

**Comment by radhermit** [comment]
All fields checked now via MetadataUrlCheck except for remote-id.
