### ISSUE TITLE
BadInsIntoDir wrongly reports subdirectories for do* stuff

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#168]
https://qa-reports.gentoo.org/output/gentoo-ci/output.html#dev-lang/rust

This is actually `insinto /etc/env.d/rust`, so it can't be replaced by `doenvd`.

**Comment by radhermit** [comment]
Already fixed by https://github.com/pkgcore/pkgcheck/commit/a39a2170b7f5da642459dce17a9c8e1f2fe508bd.
