### ISSUE TITLE
Report unnecessary dodir before dirinto etc.

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#169]
Obviously we can't catch all the cases but I think we could semi-reasonably catch ebuilds that call `dodir` and then `insinto` (`exeinto`, etc.) with the same path.

**Comment by radhermit** [comment]
I'm assuming you mean on consecutive lines? Otherwise this gets into bash parsing territory.

**Comment by mgorny** [comment]
Yeah, I guess potential conditional blocks are going to be a pain.
