### ISSUE TITLE
Is MissingUseDepDefault properly working?

### ISSUE THREAD

**Issue by Whissi** [pkgcore/pkgcheck#172]
Please see https://qa-reports.gentoo.org/output/gentoo-ci/d632650/output.html#dev-lang/php

For some reason pkgcore wants to use `=virtual/imap-c-client-1` which cannot work because `USE=kerberos` is only available in `=virtual/imap-c-client-2` which is available for all keyworded dev-lang/php ebuilds so there shouldn't be a problem...

Warning will go away when you drop `=virtual/imap-c-client-1` from repository.

**Comment by mgorny** [comment]
This is the wrong solution. PMS says that matching dep *must* be present by the target, otherwise the whole version should be ignored, even with `-flag` on php.

**Comment by radhermit** [comment]
I think by the fact that there aren't any 'foo(+)=' use deps in the tree and barely any 'foo(-)=' that there usage/interaction isn't clear to pretty much everyone.

**Comment by radhermit** [comment]
Specifically speaking for this case, you think the solution is to change the dep to something like 'virtual/imap-c-client[kerberos(+)=,ssl=]' or version limit it?

For me, it seems like the 'foo=' use dep already guarantees this because packages missing a USE flag cannot enable it. Therefore, it means you can install php with kerberos disabled with virtual/imap-c-client-1 or php with kerberos disabled or enabled with virtual/imap-c-client-2.

**Comment by mgorny** [comment]
According to the spec, you can't install it at all for -1. It is equivalent to 'author didn't check which one is correct, so you shouldn't risk '

**Comment by radhermit** [comment]
Which part of the spec implies this? I can't seem to find what you're talking about.

Also in terms of dep resolution, after playing around with example cases it seems that both portage and pkgcore currently operate how I laid out in my previous comment.

**Comment by mgorny** [comment]
https://projects.gentoo.org/pms/7/pms.html#x1-790008.2.6.4

> Unless a 4-style default is specified, it is an error for a use dependency to be applied to an ebuild which does not have the flag in question in IUSE_REFERENCEABLE.

**Comment by mgorny** [comment]
It seems that I recalled wrong. It's not supposed to cause the dependency to be ignored, it's an error altogether to do it in the first place, so the ebuild doing it may be rejected.

**Comment by radhermit** [comment]
Ah right, that makes sense. Guess I'll revert things then, thanks.

**Comment by radhermit** [comment]
@Whissi, meaning you'll probably have to fix the issue now as it won't be going away in CI.
