### ISSUE TITLE
Add a check for missing python_check_deps() function

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#176]
The any-r1 API requires using both `python_gen_any_dep` and declaring `python_check_deps()` at the same time. It would be useful if we could detect if people doing are one and not the other.

I suppose for the former, it would be sufficient to do a dumb match on `$(python_gen_any_dep`. Seems unlikely enough to occur unexpected.

For the latter, would be nice to actually check global functions but I suppose a dumb regexp `python_check_deps\s*()` would also help.

**Comment by radhermit** [comment]
While waiting for proper bash parsing, pkgcheck could use a custom bash pkg source that leverages the ebd from pkgcore and provides various bash features such as a global function list dump. In essence, it would work similar to how the PerlCheck does except it would communicate with a bash-based daemon.

I don't think it shouldn't be overly slow as long as we keep the native bash functionality to a minimum in addition to spawning multiple ebds for multiprocess scanning to make use of.

**Comment by radhermit** [comment]
It would probably be even better to include defined functions as part of extended metadata dumps under the current design, however, I think the related discussion for that kind of stalled/died a while ago.
