### ISSUE TITLE
Add a check for https://www.gentoo.org as homepage

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#177]
Some developers keep adding `https://www.gentoo.org` as homepage for Gentoo-related projects. This is useless as that homepage doesn't help users find the project in question — in fact, it is extremely hard to find *anything* from there.

**Comment by radhermit** [comment]
What's the correct homepage to use for dead upstreams? It seems like a lot of pkgs in the tree change HOMEPAGE to https://www.gentoo.org in that case. If it should be something different it would probably be good to make a note of that in the devmanual or similar so I can point the docs at that.

**Comment by mgorny** [comment]
https://devmanual.gentoo.org/ebuild-writing/variables/index.html already answers that.

**Comment by radhermit** [comment]
Ah nevermind, I see the devmanual already says to use https://wiki.gentoo.org/wiki/No_homepage.
