### ISSUE TITLE
git: implement more GLEP 66 checks

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#186]
Since pkgcheck is now checking commit message summary prefix, it'd be nice to integrate some more GLEP 66 checks that are present in repoman:

- making sure that summary is a single line,
- checking that it fits <= 69 chars (repoman also accepts pkg: + 50 chars in case pkg was very long),
- checking that body is wrapped at 80 chars (with exception if body has only one word -- then it's probably URI or some identifier we can't wrap),
- making sure there's only one footer (i.e. that all footer tags occur in one block, without empty lines in between),
- forbidding `Gentoo-Bug`,
- making sure `Bug` and `Closes` specify URL, not number.

One thing missing in repoman but still would be useful:
- making sure `Fixes` is used to reference commit id, not bug URL or number (in infra hooks we check whether it starts with at least 8 hex digits ­— but I suppose you could even verify whether it's in git history).

**Comment by radhermit** [comment]
I'd like to figure out a sane way to add proper git check and result testing before adding too much additional git-related support so I'll probably try to do that work along with this type of request.

**Comment by juippis** [comment]
- Check for **proper** sign-off syntax. There are currently some PRs with sign-offs missing `< >` around e-mail addresses.

**Comment by radhermit** [comment]
> * Check for **proper** sign-off syntax. There are currently some PRs with sign-offs missing `< >` around e-mail addresses.

Just to note, none of these checks really matter atm in relation to github PRs since afaik contributors are still pointed to use repoman by docs and these git-related checks are only run on local systems when --commits is used, i.e. not by CI.

**Comment by mgorny** [comment]
But we do use it to verify their commits ;-).

**Comment by radhermit** [comment]
> But we do use it to verify their commits ;-).

Fair enough, in that case I'd also point out that these checks should be some of the easiest to submit as a PR since all that's mostly done is various mangling/regexing of the commit.message attribute.

**Comment by radhermit** [comment]
I think most of these are done now except for some of the tag specific stuff.

**Comment by radhermit** [comment]
> * Check for **proper** sign-off syntax. There are currently some PRs with sign-offs missing `< >` around e-mail addresses.

This should already be working since git enforces 'name <email>' format for author/committer fields and pkgcheck uses those to match against. I don't think it's worth reverifying that format if git is already handling it.

**Comment by radhermit** [comment]
Closing since Fixes/Reverts tag verification was added in https://github.com/pkgcore/pkgcheck/commit/ae131acaaea4bcd06a03269df2305a9aa230ad5d which should cover the requested features.

Please open new issues if I missed something or some type of tag verification is broken.
