### ISSUE TITLE
RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used   self.stderr = io.open(errread, 'rb', bufsize)

### ISSUE THREAD

**Issue by ConiKost** [pkgcore/pkgcheck#187]
Using python3.8, I am getting on each scan a warning issued.
With older python versions, like python3_7, I am not getting such warning.

```
/usr/lib/python3.8/subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
```

**Comment by radhermit** [comment]
Closing since this is already fixed in https://github.com/pkgcore/pkgcheck/commit/714c016381b53246b449dd9c3116811e50db744f, just not in a release yet.

**Comment by ConiKost** [comment]
Thanks!
