### ISSUE TITLE
MissingSignOff on every 'pkgcheck scan --commits'

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#191]
Hey, 

I tried searching for "MissingSignOff" and didn't find any other issues. Whenever I run `pkgcheck scan --commits` after committing and before pushing to repo, I get 
```
  MissingSignOff: commit 927e4289b9b, missing sign-off: Joonas Niilola <juippis@gentoo.org>
  MissingSignOff: commit 8d74bd2f157, missing sign-off: Joonas Niilola <juippis@gentoo.org>
```
Although when amending or pushing, the sign-off is properly there. This doesn't bother me much since it doesn't disallow me from committing, but I'd like to know what's causing it.

**Comment by radhermit** [comment]
Are you running pkgcheck-0.7.2 that was just released?

**Comment by juippis** [comment]
Pfft I am now and it seems to work :)

Thanks!
