### ISSUE TITLE
MissingVirtualKeywords gets virtual/linux-sources (A || ( B C D )) wrong

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#195]
```
RDEPEND="
	firmware? ( sys-kernel/linux-firmware )
	|| (
		sys-kernel/gentoo-sources
		sys-kernel/vanilla-sources
		sys-kernel/ck-sources
		sys-kernel/git-sources
		sys-kernel/hardened-sources
		sys-kernel/mips-sources
		sys-kernel/pf-sources
		sys-kernel/rt-sources
		sys-kernel/xbox-sources
		sys-kernel/zen-sources
		sys-kernel/aufs-sources
		sys-kernel/raspberrypi-sources
		sys-kernel/vanilla-kernel
		sys-kernel/vanilla-kernel-bin
	)"
```

It produces:
```
  MissingVirtualKeywords: version 3-r3: missing KEYWORDS: arm64, mips, s390, sh
```

However, those keywords are present on linux-firmware only, and not on actual kernels, so they can't really satisfy the virtual.

**Comment by radhermit** [comment]
How is pkgcheck supposed to know that and differentiate here?

**Comment by radhermit** [comment]
I'd further question why that use flag is even necessary, but I'm biased as I don't use any of Gentoo's kernel or firmware packages.

**Comment by mgorny** [comment]
> How is pkgcheck supposed to know that and differentiate here?

I suppose it could check all arches for nonsatisfiable depgraph, i.e. like NonsolvableDeps*, except checking the missing keywords. I.e. if it has `~amd64`, then you'd check `amd64` and all other arches, and report missing keyword if it satisfies depgraph on all profiles of requested type.

**Comment by radhermit** [comment]
I think this should be fixed now with the switch from MissingVirtualKeywords to VirtualKeywordsUpdate in https://github.com/pkgcore/pkgcheck/commit/4c15429325b7221937b0a541590019f10154b332. It still doesn't do full deptree scans like it probably should, but the implementation is more pessimistic about viable keywords and thus cares about false positives over false negatives.
