### ISSUE TITLE
Check for obsolete setuptools dependencies w/ DISTUTILS_USE_SETUPTOOLS

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#198]
The idea is to report if ebuild has explicit dependency on `dev-python/setuptools` that is redundant wrt `DISTUTILS_USE_SETUPTOOLS`.

**Comment by mgorny** [comment]
s/redundant/& or mismatched/

**Comment by arthurzam** [comment]
Since transition to PEP517 for python ebuilds, this is not needed any more
