### ISSUE TITLE
Report short <longdescription/>

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#205]
Here's a brave idea: some people are meaninglessly copying DESCRIPTION into longdescription, or just putting in random short text there. Maybe we could warn, for a start over longdescriptions that are so short they would fit in DESCRIPTION easily?

**Comment by radhermit** [comment]
Isn't part of the issue that people using vim with gentoo-syntax installed get the field auto-added empty by default so perhaps they think they need to put something in there? Or has that functionality of gentoo-syntax changed recently to not add that?

**Comment by mgorny** [comment]
I've removed it from the template already, and released the new version this month.
