### ISSUE TITLE
develop a pkgcheck-based github CI action

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcheck#209]
Now that github action support is slowly getting fleshed out it could be interesting to have an official pkgcheck CI action that people could hook into for CI checks against 3rd party overlays hosted on github.

For the action, it probably would make the most sense to use a tarball-based syncer for the gentoo repo and make sure the repo/pkgcheck caches were properly saved/restored across runs to cut down on init time.

**Comment by radhermit** [comment]
Another thing to note is that this would require exit status support (https://github.com/pkgcore/pkgcheck/issues/28) in order for the action to fail out properly when detecting certain classes of issues. Obviously that should be configurable but also have sane defaults so setting it wouldn't be necessary -- any result with an error level would cause the action to fail.

**Comment by gyakovlev** [comment]
I started simple travis setup here https://github.com/gyakovlev/pkgcheck-my-overlay
and of course got blocked by absence of non-zero return code on exit if check failed.
idea is to provide not only travis, but also other CI configurations for different platforms so people can copy files into their repos (github, gitlab, cirrusCI and others)

**Comment by radhermit** [comment]
Configurable exit status support has been added via the ``pkgcheck scan --exit`` option in https://github.com/pkgcore/pkgcheck/commit/b7f3c1b6bbd4355c46d5f1ae15df205d81e522a4 so CI support with configurable error results should now be possible.

**Comment by radhermit** [comment]
> I started simple travis setup here https://github.com/gyakovlev/pkgcheck-my-overlay
> and of course got blocked by absence of non-zero return code on exit if check failed.
> idea is to provide not only travis, but also other CI configurations for different platforms so people can copy files into their repos (github, gitlab, cirrusCI and others)

I started the [pkgcheck-ci](https://github.com/pkgcore/pkgcheck-ci) repo to provide similar support with an initial travis-ci integration example. Feel free to merge efforts and submit PRs for other services if you want.

**Comment by radhermit** [comment]
Closing this since github action related work will occur in the https://github.com/pkgcore/pkgcheck-action repo from now on.
