### ISSUE TITLE
MatchingChksums false positives: go.mod files

### ISSUE THREAD

**Issue by robbat2** [pkgcore/pkgcheck#228]
`MatchingChksums` gives lots of false positives on `go.mod` files, e.g.
```
distfile 'cloud.google.com%2Fgo%2F@v%2Fv0.34.0.mod' matches checksums for 'cloud.google.com%2Fgo%2F@v%2Fv0.26.0.mod' from app-admin/consul
```

If they match, it means the dependencies for the Go package (`cloud.google.com/go` in this case) involved haven't changed. The associated zipfiles will have changed.

For the moment, I'd suggest if the Distfile in Manifest matches the regex of `%2F@V.*mod`, then disable MatchingChksums for that case.

**Comment by mgorny** [comment]
It's not a false positive. It's a bad design that's causing lots of waste on duplicate files.

**Comment by robbat2** [comment]
The only alternatives would be:
- hash by file content
- embed the file content into ebuilds
- always download the `.zip` file even if it's not needed, and extract just the `.mod`

All of which impose significant cost on the Gentoo package maintainer.

The decisions of Upstream do suck here, but these files present part of the dependency contract between upstream packages.

Overall, right now, this affects 761 distfiles unique by content, that have 1694 unique names: average of 2.23 times each. Those distfiles appear ~6200 times in the tree.

One of the outliers is `golang.org%2Fx%2Fsys%2F@v%2Fv0.0.0-.*.mod` which appears ~180 times with ~65 differ names because the API isn't stable yet.

**Comment by radhermit** [comment]
In an ideal world I'd like to see upstreams be convinced to make bundled source tarballs with all deps in the vendor dir or however that works now for go projects. To me, this is similar to python package upstreams not including their tests (or test data) in source tarballs.

**Comment by radhermit** [comment]
I should note that I meant in an ideal, *go-centric* world. In a truly ideal world deps probably shouldn't need to be bundled.
