### ISSUE TITLE
traceback on bad mirror value

### ISSUE THREAD

**Issue by msterret** [pkgcore/pkgcheck#23]
ERROR root: check <pkgcheck.repo_metadata.ManifestReport object at 0x7f1d2094e6d0> raised
ERROR root: Traceback (most recent call last):
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/base.py", line 337, in feed
ERROR root:     check.feed(item, reporter)
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcheck/repo_metadata.py", line 242, in feed
ERROR root:     pkg._get_attr['fetchables'](pkg, allow_missing_checksums=True),
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py", line 89, in generate_fetchables
ERROR root:     allow_src_uri_file_renames=self.eapi_obj.options.src_uri_renames)
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/conditionals.py", line 188, in parse
ERROR root:     raise_from(ParseError(dep_str, e))
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/conditionals.py", line 164, in parse
ERROR root:     depsets[-1].append(element_func(k))
ERROR root:   File "/usr/lib64/python2.7/site-packages/pkgcore/ebuild/ebuild_src.py", line 121, in create_fetchable_from_uri
ERROR root:     raise UnknownMirror(tier, remaining_uri)
ERROR root: ParseError: mirror://berlios/gnomeboyadvance/gnomeboyadvance-0.1.tar.bz2 is unparseable
ERROR root: flagged token- uri mirror://berlios/gnomeboyadvance/gnomeboyadvance-0.1.tar.bz2 isn't a known mirror tier

could be handled better.

**Comment by radhermit** [comment]
I think this should be fixed in 5de0d3378222f1066814ac8dad44aa911b1a3dc5 so just reinstall the latest pkgcore/pkgcheck and you should be good, otherwise please reopen this.
