### ISSUE TITLE
UnstableOnly / PotentialStable are fired on unstable-only arches

### ISSUE THREAD

**Issue by trofi** [pkgcore/pkgcheck#230]
`ia64` does not have stable keywords nowadays. Yet, `pkgcheck` flags it as potentially stable:

```
$ pkgcheck scan sys-libs/libunwind
sys-libs/libunwind
  UnstableOnly: for arch: [ ia64 ], all versions are unstable: [ 1.2.1-r3, 1.4.0 ]
  PotentialStable: version 1.2.1-r3: slot(0), stabled arches: [ amd64, arm, arm64, hppa, ppc, ppc64, x86 ], potential: [ ~ia64 ]
```

**Comment by radhermit** [comment]
IIRC without looking at the code, both results check all arches that have stable profiles which ia64 still appears to have.

**Comment by radhermit** [comment]
The implication being unstable arches probably shouldn't have stable profiles.

**Comment by mgorny** [comment]
We need to implement the new GLEP.

**Comment by radhermit** [comment]
Initial GLEP 72 work done via https://github.com/pkgcore/pkgcore/commit/e18c7ecf11f916ba2f57659a20f6e1b6dfb4853a. Next up would be threading that support into relevant pkgcheck locations.
