### ISSUE TITLE
Please document --domain more clearly

### ISSUE THREAD

**Issue by kentfredric** [pkgcore/pkgcheck#234]
```
--domain DOMAIN

    domain to use for this operation
```

This is not really helpful to understand what it expects, and trying to work out what I've done, and what I need to do when I see this:

```
pkgcheck: error: config error: no default object of type 'domain' found.  Please either fix your configuration, or set the domain via the --domain option
```

Is somewhat impossible.

**Comment by radhermit** [comment]
It might mean your portage config is unsupported in some fashion by pkgcore possibly combined with some config handling bug. Try running ``pconfig dump`` and see if you get anything.

External domain support should probably be removed since if I recall correctly it's from a plan over a decade old of a more grand vision for how pkgcore could be made to operate on disparate envs which isn't likely to happen anymore.

**Comment by kentfredric** [comment]
```bash
# pkgcheck dump
pkgcheck: error: argument subcommand: invalid choice: 'dump' (choose from 'scan', 'cache', 'replay', 'show')
```

And what I'm doing that causes the error:

```bash
# pkgcheck --config ~/.config/pkgcheck/pkgcheck.conf scan
pkgcheck: error: config error: no default object of type 'domain' found.  Please either fix your configuration, or set the domain via the --domain option.

**Comment by radhermit** [comment]
I said ``pconfig dump`` not ``pkgcheck dump``, but if you're using an external config file attaching/outputting that somewhere would be helpful as well.

**Comment by kentfredric** [comment]
```bash
# pconfig --config ~/.config/pkgcheck/pkgcheck.conf dump
'basic' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.BasicFormatter;
}

'paludis' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PaludisFormatter;
}

'pkgcore' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PkgcoreFormatter;
}

'portage' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PortageFormatter;
    default true;
}

'portage-verbose' {
    # typename of this section: pmerge_formatter
    class pkgcore.ebuild.formatter.PortageVerboseFormatter;
}
```

Though I'm guessing I made a critical mistake:

`pkgcheck --config=<foo> scan`

Instead of 

`pkgcheck scan --config=<foo>`

Which may do different things.

```ini
[DEFAULT]
repo = /usr/local/gentoo
arches = alpha,amd64,arm64,hppa,ia64,m68k,mips,ppc,ppc64,riscv,s390,sparc,x86,ppc-aix,amd64-linux,arm-linux,arm64-linux,ppc64-linux,x86-linux,ppc-macos,x86-macos,x64-macos,m68k-mint,sparc-solaris,sparc64-solaris,x64-solaris,x86-solaris,x64-winnt,x86-winnt,x64-cygwin,x86-cygwin
source-arches = alpha,amd64,arm64,hppa,ia64,m68k,mips,ppc,ppc64,riscv,s390,sparc,x86,ppc-aix,amd64-linux,arm-linux,arm64-linux,ppc64-linux,x86-linux,ppc-macos,x86-macos,x64-macos,m68k-mint,sparc-solaris,sparc64-solaris,x64-solaris,x86-solaris,x64-winnt,x86-winnt,x64-cygwin,x86-cygwin
reporter = FancyReporter
checks = all
glsa-dir = /usr/portage/metadata/glsa/
keywords = error,warning,info
scopes = git,profiles,eclass,repo,cat,pkg,ver
profiles = all
```

**Comment by radhermit** [comment]
Yes, you are correct in terms of the --config option ordering.

**Comment by kentfredric** [comment]
That's rather unfortunate really from an API perspective. I'm not sure what can be done to make that more obvious from error-handling perspective, other than some simple pre-parse that validates the basic format and goes "hey, that doesn't look like our config, maybe you got the params in the wrong place" ( but only when the parse looks valid for the other place )

**Comment by radhermit** [comment]
Easiest way to alleviate that a bit would be to rename ``pkgcheck scan --config`` to something like ``pkgcheck scan --conf`` so there isn't option name overlap.

**Comment by radhermit** [comment]
This https://github.com/pkgcore/pkgcore/commit/8f666ec13c5d8fb347f2c8463fefe4453e1b0a69 might also help a bit to disambiguate the options.

**Comment by radhermit** [comment]
I've added more specific help message output to help users tell the difference between the options. That's about the best you'll get in the short term since doing more config related stuff probably requires a rethinking/simplification/rewrite of config handling for pkgcore in general.
