### ISSUE TITLE
False positive for MissingSignOff

### ISSUE THREAD

**Issue by orlitzky** [pkgcore/pkgcheck#235]
pkgcheck complains about this commit:

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=7311a1368de9aa10d9a92b0e23fc4bd74e0838ee

most likely due to the author name mismatch:

```
$ pkgcheck scan --commits
updating gentoo git repo cache: f3c38f162d41b -> 1cdabc307639b
sci-libs/fplll
  DeprecatedEapi: version 4.0.4: uses deprecated EAPI 5
  DeprecatedEclass: version 4.0.4: uses deprecated eclass: [ ltprune (no replacement) ]
  RedundantVersion: version 4.0.4: slot(0) keywords are overshadowed by versions: 5.3.2, 5.3.3

commit
  MissingSignOff: commit 7311a1368de, missing sign-off: François Bissey <frp.bissey@gmail.com>
```

That looks legal according to GLEP 76, which asks for your full legal name. But is it worth fixing, or no?

**Comment by radhermit** [comment]
The check wants the names to match between the commit author and sign-off which I think is a legitimate request.

**Comment by radhermit** [comment]
To clarify, I don't think most people are including their middle name(s) for GLEP 76 signoffs even if they have them, just <first> <last>.
