### ISSUE TITLE
Check for PYTHON_COMPAT upgrade possibility

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#240]
Roughly the idea is to:

1. Grab all available PYTHON_TARGETS (via .desc), filter to `python*`, sort by version.
2. Filter out targets that are masked.
3. Select targets that are newer than the newest target in PYTHON_COMPAT (obtained e.g. via scanning IUSE).
4. Check that all package dependencies that reference in USE-deps the newest target currently in PYTHON_COMPAT also support the newer targets (i.e. drop the newer targets that aren't supported by deps).
5. If at least one target remained, report possible upgrade.

**Comment by radhermit** [comment]
This doesn't sound overly difficult as it mainly involves flattening dep trees and verifying set inclusion for use deps, both of which should already have examples in other checks.
