### ISSUE TITLE
BadCommitSummary check for category-level commits

### ISSUE THREAD

**Issue by perfinion** [pkgcore/pkgcheck#250]
When I bump the SELinux policies they must all be bumped together. I basically commit all `sec-policy/selinux-*/*-2.20200818-r2.ebuild` in one giant commit instead of doing 257 one liners. (There is single other non-selinux package in the category is apparmor-profiles)

`pkgcheck scan --commits` tell me this line many times (I suspect once per package but haven't counted):

```BadCommitSummary: commit 26fd6614689, summary missing matching package prefix: 'sec-policy: Stabilize SELinux policy 2.20200818-r2'```

When we migrated cvs->git the best practices said either use `cat/pkgname: foo` or `cat: foo` as the title but I can't find any references to that anymore. Can the check be changed so `cat: ` is a valid prefix for commits that contain files from more than one package? Dropping the check is possible too but I'd prefer to still have it check the category prefix if that's not too much work.

Thanks!

**Comment by radhermit** [comment]
This should be possible with some rework that should happen anyway in order to keep all commit message checks in the same place.
