### ISSUE TITLE
After setting RESTRICT="bindist mirror !test? ( test )", pkgcheck fails to find any of the three

### ISSUE THREAD

**Issue by epsilon-0** [pkgcore/pkgcheck#259]
Case in point, the ebuild for arrayfire at https://github.com/gentoo/sci/blob/master/sci-libs/arrayfire/arrayfire-3.7.2.ebuild

which has: `RESTRICT="bindist mirror !test? ( test )"`

pkgcheck complains:
```
sci-libs/arrayfire
  MissingLicenseRestricts: version 3.7.2: EULA license 'OpenSIFT' requires RESTRICT="bindist mirror"
  MissingTestRestrict: version 3.7.2: missing RESTRICT="!test? ( test )" with IUSE=test
```

**Comment by radhermit** [comment]
Closing this since that ebuild overrides RESTRICT further in the ebuild with RESTRICT="userpriv". Combine the restrictions properly and pkgcheck should operate as expected.
