### ISSUE TITLE
Fatal Error with bad `make.profile` symlink in `/etc/portage`

### ISSUE THREAD

**Issue by kentfredric** [pkgcore/pkgcheck#272]
For some reason long lost to history, I had a `make.profile` symlink in `/etc/portage`, which was a dead relative symlink to `../usr/portage/profiles/ ... /13.0`

Until my last pkgcore/pkgcheck/snakeoil update, neither portage or pkgcore family saw any issue with this, despite it being dead for several years.

`eselect profile` didn't find anything wrong with this either, as it was actually only tweaking `/etc/make.profile`, and that's what portage was using.

But until I fixed the symlink not to be dead, this error didn't occur in eselect profile:

!!! Warning: Both /etc/make.profile and /etc/portage/make.profile exist.
!!! Warning: Using /etc/portage/make.profile.

As I imagine "dead symlink" is pathed as "not exists" in portage code.

And the fallout with some augmented strace was as follows:
```
readlink("/etc/portage/make.profile", "../usr/portage/profiles/default/linux/amd64/13.0", 4096) = 48
readlink("/etc/usr/portage/profiles/default/linux/amd64/13.0", 0x7ffe2850bcc0, 4096) = -1 ENOENT (No such file or directory)
readlink("/etc/usr/portage/profiles/default/linux/amd64/13.0", 0x7ffe2850bcc0, 4096) = -1 ENOENT (No such file or directory)
stat("/usr/local/portage/profiles", {st_dev=makedev(0x8, 0x6), st_ino=1156100, st_mode=S_IFDIR|0775, st_nlink=2, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=1611205633 /* 2021-01-21T18:07:13.044465992+1300 */, st_atime_nsec=44465992, st_mtime=1604820979 /* 2020-11-08T20:36:19.576695747+1300 */, st_mtime_nsec=576695747, st_ctime=1604820979 /* 2020-11-08T20:36:19.576695747+1300 */, st_ctime_nsec=576695747}) = 0
stat("/usr/local/portage/metadata", {st_dev=makedev(0x8, 0x6), st_ino=1156099, st_mode=S_IFDIR|0775, st_nlink=2, st_uid=1000, st_gid=1000, st_blksize=4096, st_blocks=8, st_size=4096, st_atime=1611205633 /* 2021-01-21T18:07:13.038465980+1300 */, st_atime_nsec=38465980, st_mtime=1586330862 /* 2020-04-08T19:27:42.252990817+1200 */, st_mtime_nsec=252990817, st_ctime=1586330862 /* 2020-04-08T19:27:42.252990817+1200 */, st_ctime_nsec=252990817}) = 0
readlink("/etc/usr/portage/profiles/default/linux/amd64/13.0", 0x7ffe2850b180, 4096) = -1 ENOENT (No such file or directory)
stat("/etc/usr/portage/profiles/default/linux/amd64/13.0", 0x7ffe2850bc20) = -1 ENOENT (No such file or directory)
pkgcheck: error: failed parsing '/etc/usr/portage/profiles/default/linux/amd64/13.0': nonexistent profile directory
```

**Comment by radhermit** [comment]
Should be fixed via https://github.com/pkgcore/pkgcore/commit/bf3009f1b963e75a58598ef1de905b4516c0442e.

The outputted error should now be ``pkgcheck: error: broken symlink: '/etc/portage/make.profile'``.
