### ISSUE TITLE
return a status code relating to whether errors were found

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcheck#28]
By default warnings and below wouldn't set an error status, but any checks that return the error class would.

**Comment by mgorny** [comment]
Can't say I'm very happy about the sudden API change. Not saying it's bad but now all scripts that relied on pkgcheck failing only when some exception happens are broken.

Could we add an option to control this? Like three-state to control whether it fails never, on error or on warning.

**Comment by radhermit** [comment]
This was mostly to mimic the behavior of repoman. Instead of making it optional couldn't you check the return status value?

**Comment by mgorny** [comment]
My scripts are run with `set -e` (or via make), so it would end up with ugly logic like:

    pkgcheck ...many-many-arguments... || [ $? -ne 1 ]

**Comment by radhermit** [comment]
Reverted for now, if/when exceptions are handled better it might be able to be re-enabled.
