### ISSUE TITLE
pkgcheck.scan() seems to hang when used with freezegun

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#294]
I'm using `freezegun` to trigger cache expiration inside nattka's tests. However, after switching to in-process `pkgcheck.scan()`, the frozen time seems to cause it to hang. I suspect it's getting confused by subprocesses coming from the future.

Trivial reproducer (run inside any ebuild directory):

```
#!/usr/bin/env python

import datetime
import freezegun
import pkgcheck

last_check = datetime.datetime.utcnow() - datetime.timedelta(days=1)
with freezegun.freeze_time(last_check):
    print(list(pkgcheck.scan(['-c', 'VisibilityCheck'])))
```

**Comment by radhermit** [comment]
I'm pretty sure this is related to freezegun and multiprocessing interaction as seen in https://github.com/spulec/freezegun/issues/230.

In others words, it sounds like a bug in freezegun.

**Comment by radhermit** [comment]
Closing since I think this should be fixed in freezegun.
