### ISSUE TITLE
Style warning for 'bump' commits w/o version

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#298]
It's not specified in [GLEP 66](https://www.gentoo.org/glep/glep-0066.html#commit-messages), but is it possible to have a check for commits which add new versions of ebuilds, but do not reference a version in the commit message?

This isn't a serious problem, but a gentle nudge would be nice (hence style).

**Comment by radhermit** [comment]
This should be possible but requires modifying the GitPkgChange dataclass object to include commit message attrs for localized usage.

Also, note that `pkgdev commit` users will already get 'bump' style commit messages for free since they're auto-generated by default under the correct conditions.
