### ISSUE TITLE
Style(?) warning for POSIX-style tests

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#302]
We should consider a style warning (at least) for using POSIX tests.

POSIX-style [] tests don't belong in ebuilds, generally. We're guaranteed to have Bash available and their behaviour differs from Bash tests with subtle gotchas.

The vast majority of tests in ebuilds are Bash - using them consistently avoids errors, rather than people needing to remember the differences between the common pattern and a rarely-seen one.

**Comment by radhermit** [comment]
These types of features start getting into the "we should just run shellcheck" kind of discussion.

**Comment by thesamesam** [comment]
Yes, you're not wrong actually.
