### ISSUE TITLE
profile-formats = portage-2 --> UnstatedIuse

### ISSUE THREAD

**Issue by AndrewAmmerlaan** [pkgcore/pkgcheck#305]
pkgcheck doesn't seem to like `profile-formats = portage-2` very much. This profile-format is useful because it allows per-profile masking in an overlay: https://github.com/gentoo/guru/pull/31 https://trofi.github.io/posts/201-masking-a-package-in-gentoo-overlay.html

However, enabling this results in pkgcheck returning errors about missing arch/prefix flags:
```
FAILURE RESULTS
/opt/hostedtoolcache/Python/3.9.2/x64/bin/pkgcheck replay --color y /home/runner/failures.json
sci-biology/ssaha2-bin
  UnstatedIuse: version 2.5.5: attr(fetchables): profile 'default/linux/amd64/17.0/x32' (1 total): unstated flags: [ amd64, x86 ]

sci-biology/trf-bin
  UnstatedIuse: version 4.09: attr(fetchables): profile 'default/linux/amd64/17.0/x32' (1 total): unstated flags: [ amd64, x86 ]

sci-chemistry/chimera-bin
  UnstatedIuse: version 1.14: attr(depend): profile 'default/linux/amd64/17.0/x32' (1 total): unstated flag: [ prefix ]
  UnstatedIuse: version 1.15: attr(depend): profile 'default/linux/amd64/17.0/x32' (1 total): unstated flag: [ prefix ]

sci-chemistry/concoord
  UnstatedIuse: version 2.1: attr(fetchables): profile 'default/linux/amd64/17.0/x32' (1 total): unstated flags: [ amd64, x86 ]
  UnstatedIuse: version 2.1.2: attr(fetchables): profile 'default/linux/amd64/17.0/x32' (1 total): unstated flags: [ amd64, x86 ]

sci-chemistry/nmrpipe
  UnstatedIuse: version 8.7.20200827: attr(rdepend): profile 'default/linux/amd64/17.0/x32' (1 total): unstated flag: [ prefix ]
```

Repoman doesn't complain about this, and it does seem to work as intended.

See commit: https://github.com/gentoo/sci/commit/3f7fad2f7170cd44f1019865604c6ed196f5b03c
And PR: https://github.com/gentoo/guru/pull/31

**Comment by AndrewAmmerlaan** [comment]
As of version 0.9.7 this is also happening in the guru overlay: https://github.com/gentoo/guru/actions/workflows/pkgcheck.yml

**Comment by radhermit** [comment]
I'll be blatantly honest, I'm leaning towards entirely dropping the various, half-broken profile-formats support pkgcore currently has. Someone should step up, do the work, and get the features they feel are important into the spec.

**Comment by radhermit** [comment]
Closing because I'm not sure all the corner/edge cases even translate to pkgcheck bugs here, it's probably more of a pkgcore issue than anything. Those interested should look into fixing/adding for tests for that in pkgcore and getting the features they want out of optional extensions and into an actual spec.
