### ISSUE TITLE
Additional checks for USE_EXPAND

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#31]
A few quick ideas:
* in unused flag report, we should also cover USE_EXPAND *.desc flags that are not used anywhere,
* we should probably have a report for packages describing USE_EXPAND locally rather than in *.desc.

**Comment by radhermit** [comment]
Is this available in repoman already? On a sidenote, it might be interesting to open an issue containing a checklist of all useful, missing repoman checks from pkgcheck so we can work towards decreasing that number.

**Comment by radhermit** [comment]
Was this all covered in #34 then?

**Comment by radhermit** [comment]
Closing since I'm assuming this was covered in #34.
