### ISSUE TITLE
BadCommitSummary summary missing category prefix wrong alert

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#312]
```
commit
  BadCommitSummary: commit cc4c1785e2c, summary missing 'net-analyzer' category prefix: 'net-analyzer/ospd-openvas: version bump to 20.8.1'
```
https://sources.gentoo.org/repo/gentoo.git/commit/?id=cc4c1785e2c3ea574cdf5b0b082e1ba47dfc1d40

I'm not seeing the error here, everything looks correct.
```
$ pkgcheck --version
pkgcheck 0.9.4
```

**Comment by juippis** [comment]
Well I see it touches `net-analyzer/ospd/ospd-20.8.2.ebuild` in the same commit, but the commit summary should still be okay.

**Comment by radhermit** [comment]
Closing since I don't agree as it looks like that should have been two separate commits.
