### ISSUE TITLE
Warn on eclasses with @DEAD but not @DEPRECATED

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#316]
```@DEAD``` is a strange option anyway because it only stops generation of eclass docs, it doesn't actually declare an eclass is deprecated. We should warn when an eclass is marked ```@DEAD``` but not ```@DEPRECATED```.

**Comment by radhermit** [comment]
The eclassdoc tag parsing support from pkgcore doesn't even recognize @DEAD. I personally don't think it's a useful flag at all.

**Comment by thesamesam** [comment]
I'm working on that: https://github.com/gentoo/devmanual/pull/214. Okay, let's just work on killing the (horrible) flag. Totally on board with that.
