### ISSUE TITLE
Force IncorrectCopyright

### ISSUE THREAD

**Issue by ezzieyguywuf** [pkgcore/pkgcheck#319]
Is there a way to force 'IncorrectCopyright' to be checked, even if `--commits` is not used?

I'm [using pkgcheck in a git pre-commit hook](https://github.com/ezzieyguywuf/git_hooks/blob/master/pre-commit_pkgcheck#L71) in order to check the list of atoms that have been touched by the commit. Unfortunately, I'm unable to check the copyright pre-commit, since pkgcheck expects `--commits` in order for this check to run.

Rather, I have a separate [pre-push hook](https://github.com/ezzieyguywuf/git_hooks/blob/master/pre-push_pkgcheck#L11) that I use to check the copyright, but then there is a "lag" between when the issue occurs and when I catch it.

Any chance this can be configurable?

**Comment by radhermit** [comment]
It's not impossible, but would require significant rework to allow source generation for staged changes to be used in addition to committed changes for relevant checks since the underlying implementation currently uses ``git log`` parsing and makes many commit-related assumptions.

**Comment by radhermit** [comment]
Closing because I don't see myself doing the work for this support since I think it's the wrong way to go about it. Instead, someone interested could look into writing python scripts for various git hooks that leverage pkgcheck natively thereby allow more extensibility and testing support.
