### ISSUE TITLE
PythonCompatCheck sorts Python 3.10 wrong

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#320]
Apparently it's using lexical sorting, and that doesn't work for py3.10.

```
['python3_10', 'python3_7', 'python3_8', 'python3_9']
```

**Comment by radhermit** [comment]
Fixed via https://github.com/pkgcore/pkgcheck/commit/12a6ca0bb62766f7674644e91378b2ab035769bf.
