### ISSUE TITLE
Check for deprecated licenses

### ISSUE THREAD

**Issue by ulm** [pkgcore/pkgcheck#325]
pkgcheck should check for deprecated licenses, as repoman does. See [bug 440638](https://bugs.gentoo.org/440638) for details.

**Comment by radhermit** [comment]
From skimming the related bug, isn't this less relevant now that as-is isn't available to be used as a license anymore?

**Comment by ulm** [comment]
It is useful for other deprecated licenses.

For example, we currently have "FreeArt" in this list. It has been renamed to "Free-Art-1.2", and I want to keep the old name for a transition time, but prevent usage of it in new ebuilds.

**Comment by ulm** [comment]
Thanks.
