### ISSUE TITLE
git cache: disable cache usage when not running against the default branch

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcheck#335]
To avoid non-linear history issues, git cache support should be disabled when it's determined the scan isn't being done in a linear fashion against the default branch for a known git cache.

**Comment by ionenwks** [comment]
This has made it harder to do branch comparison, it's giving me non-reproducible warnings (like nonexistentblocker) when not on default branch. Is there a way at most optionally make it use cache anyway? (do not wish to override those specific checks either).
