### ISSUE TITLE
"pgkcheck scan" fails in the presence if "gpg: " information in "git log"

### ISSUE THREAD

**Issue by Flowdalic** [pkgcore/pkgcheck#336]
For my overlay repository, `git log` output looks like the following:

```
commit 944fcc5b4d27da23fbb7154143e97e72addd50c6 (HEAD -> master, origin/master, origin/HEAD)
gpg: Signature made 2021-07-22T15:36:41 CEST
gpg:                using RSA key 9775059F3A21DCE16BE4FBAE2239A7E8F5852052
gpg: Good signature from "Florian Schmaus <flo@geekplace.eu>" [ultimate]
gpg:                 aka "Florian Schmaus <flo@freakempire.de>" [ultimate]
gpg:                 aka "Florian Schmaus <flow@gentoo.org>" [ultimate]
Author: Florian Schmaus <flow@gentoo.org>
Date:   Thu Jul 22 15:36:35 2021 +0200

    x11-wm/herbstluftwm: update

commit 8897e400c4d752859d57d0bfc2c38676d3db3d64
gpg: Signature made 2021-07-19T19:58:11 CEST
gpg:                using RSA key 9775059F3A21DCE16BE4FBAE2239A7E8F5852052
gpg: Good signature from "Florian Schmaus <flo@geekplace.eu>" [ultimate]
gpg:                 aka "Florian Schmaus <flo@freakempire.de>" [ultimate]
gpg:                 aka "Florian Schmaus <flow@gentoo.org>" [ultimate]
Author: Florian Schmaus <flow@gentoo.org>
Date:   Mon Jul 19 19:58:11 2021 +0200

    x11-misc/rofi-file-browser-extended: treeclean
```

However, the prensence of the "gpg: " lines, seems to trip off `pgkcheck`. Invoking `pkgcheck scan. ` gives the following backtrace:

```
$ pkgcheck scan .
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkgcheck/addons/__init__.py", line 288, in init_addon
    addon = addons_map[cls]
KeyError: <class 'pkgcheck.addons.git.GitAddon'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pkgcheck/addons/git.py", line 210, in __next__
    return self._pkgs.popleft()
IndexError: pop from an empty deque

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/pkgcheck", line 4, in <module>
    scripts.run(basename(__file__))
  File "/usr/lib/python3.8/site-packages/pkgcheck/scripts/__init__.py", line 38, in run
    sys.exit(tool())
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 79, in __call__
    ret = self.main()
  File "/usr/lib/python3.8/site-packages/pkgcheck/cli.py", line 21, in main
    return super().main()
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 185, in main
    self.handle_exec_exception(e)
  File "/usr/lib/python3.8/site-packages/snakeoil/cli/tool.py", line 170, in main
    exitstatus = func(self.options, self.out, self.err)
  File "/usr/lib/python3.8/site-packages/pkgcheck/scripts/pkgcheck_scan.py", line 431, in _scan
    pipe = Pipeline(options)
  File "/usr/lib/python3.8/site-packages/pkgcheck/pipeline.py", line 36, in __init__
    self._pipes = self._create_runners()
  File "/usr/lib/python3.8/site-packages/pkgcheck/pipeline.py", line 92, in _create_runners
    checks = init_checks(
  File "/usr/lib/python3.8/site-packages/pkgcheck/checks/__init__.py", line 187, in init_checks
    addon = addons.init_addon(cls, options, addons_map)
  File "/usr/lib/python3.8/site-packages/pkgcheck/addons/__init__.py", line 307, in init_addon
    addon.update_cache(force=force_cache)
  File "/usr/lib/python3.8/site-packages/pkgcheck/addons/git.py", line 522, in update_cache
    self.pkg_history(
  File "/usr/lib/python3.8/site-packages/pkgcheck/addons/git.py", line 482, in pkg_history
    for pkg in GitRepoPkgs(repo.location, commit_range, local=local):
  File "/usr/lib/python3.8/site-packages/pkgcheck/addons/git.py", line 213, in __next__
    commit_time = int(next(self.git_log).rstrip('\x00'))
ValueError: invalid literal for int() with base 10: 'gpg: Good signature from "Florian Schmaus <flo@geekplace.eu>" [ultimate]'
```

**Comment by radhermit** [comment]
A link to your overlay would be nice if it's public in order to reproduce/test, I'm too lazy to go searching. :smile:

**Comment by radhermit** [comment]
I'm going to guess you have ``log.showSignature`` enabled in your system config, user config, or the repo's git config. I'm unsure how to make ``git log`` ignore that setting or override it if you have it in the repo config since it only provides a setting to turn it on, but system and user configs are now ignored. If you have it in the repo config, I'd advise disabling it or figuring out how to conditionally disable it and post it to this issue or create a PR if you want to use pkgcheck's git support.

**Comment by Flowdalic** [comment]
Thanks for the quick fix. :)

> I'd advise disabling it or figuring out how to conditionally disable it and post it to this issue or create a PR if you want to use pkgcheck's git support.

I actually have it in the repos config. While simply disabling it there and move it to the user config, I do wonder if another option could be to simply have `next()` (or maybe the affected call sites?) ignore all lines starting with 'gpg: '. Would that be an agreeable additional measurement to further increase the robustness of pkgcore's git output parsing?

**Comment by radhermit** [comment]
> I actually have it in the repo's config. While simply disabling it there and move it to the user config, I do wonder if another option could be to simply have `next()` (or maybe the affected call sites?) ignore all lines starting with 'gpg: '. Would that be an agreeable additional measurement to further increase the robustness of pkgcore's git output parsing?

Inserting specific workarounds for random config settings isn't something I agree with.

I'd rather have a solution similar to one of the following: some type of option for `git log` to ignore all config settings, some variable to ignore local repo settings, or for libraries like pygit2 to not be an order of magnitude slower for log diffing compared to running git itself so it could be used instead.
