### ISSUE TITLE
pkgcheck scan: error: repo init failed: repo ... has missing masters: 'gentoo'

### ISSUE THREAD

**Issue by leycec** [pkgcore/pkgcheck#342]
Hi! This is @leycec, the [plucky maintainer of the dodgy `raiagent` overlay](https://github.com/leycec/raiagent) and frequent contributor to the [*incredible* science overlay](https://github.com/gentoo/sci). I've been eyeing `pkgcheck scan` as a drop-in CI replacement for `repoman`, which I increasingly loathe with deep and abiding hatred.

Sadly, `pkgcheck scan` refuses to locally do anything:

```
$ git clone https://github.com/leycec/raiagent.git
Cloning into 'raiagent'...
remote: Enumerating objects: 3889, done.
remote: Counting objects: 100% (652/652), done.
remote: Compressing objects: 100% (461/461), done.
remote: Total 3889 (delta 324), reused 442 (delta 169), pack-reused 3237
Receiving objects: 100% (3889/3889), 1.04 MiB | 334.00 KiB/s, done.
Resolving deltas: 100% (1829/1829), done.
$ cd raiagent
$ pkgcheck --version
pkgcheck 0.10.3
$ pkgcheck scan
pkgcheck scan: error: repo init failed: repo 'raiagent' at path
'/home/leycec/tmp/raiagent' has missing masters: 'gentoo'
```

It... doesn't inspire confidence. I've probably misconfigured my overlay and/or system in some horrifying way. Still, `pkgcheck scan` isn't exactly being communicative, intelligible, or useful about the underlying issue – whatever the underlying issue even is.

Suspiciously, commenting out the `masters = gentoo` line from the `metadata/layout.conf` file superficially fixes everything:

```
# After cutting "masters = gentoo", "pkgcheck" wakes up.
$ pkgcheck scan
repo
  UnusedLicenses: unused licenses: BOSL-1.1, MAME, TSL, UNICODE, UNREAL-WORLD, i2p, pyinstaller, seventh-sense, shockbolt-tileset

profiles
  NonexistentCategories: nonexistent profiles/categories entry: app-lyx
  OldPackageUpdate: 'dev-python/pyside2' unavailable: old update line: 'move dev-python/pyside dev-python/pyside2'
  OldPackageUpdate: 'dev-python/pyside2-tools' unavailable: old update line: 'move dev-python/pyside-tools dev-python/pyside2-tools'
  OldPackageUpdate: 'dev-python/shiboken2' unavailable: old update line: 'move dev-python/shiboken dev-python/shiboken2'
  OldPackageUpdate: 'media-sound/munt' unavailable: old update line: 'move media-libs/munt media-sound/munt'
  UnknownProfilePackage: 'arch/powerpc/package.use.mask': unknown package: 'app-misc/powerline'
  UnknownProfilePackage: 'package.mask': unknown package: '~media-libs/libsdl-1.2.9999'
  UnknownProfilePackage: 'package.unmask': unknown package: '<=dev-python/contextlib2-9999'
  UnknownProfilePackage: 'package.unmask': unknown package: '<=dev-python/flask-socketio-9999'
  UnknownProfilePackage: 'package.unmask': unknown package: '<=dev-python/pysha3-9999'
  UnknownProfilePackage: 'package.unmask': unknown package: '<=dev-python/pytest-qt-9999'
  UnknownProfilePackage: 'package.unmask': unknown package: '<=dev-python/python-engineio-9999'
  UnknownProfilePackage: 'package.unmask': unknown package: '<=dev-python/python-socketio-9999'
  UnusedProfileDirs: unused profile dirs: 'arch', 'arch/powerpc'
```

Of course, I'm pretty sure that `masters = gentoo` is *literally* mandatory for overlays. Permanently removing that seems like a non-starter. The GURU repository has a [similar `metadata/layout.conf` file](https://github.com/gentoo-mirror/guru/blob/master/metadata/layout.conf) and a [seemingly working `pkgcheck` CI configuration](https://github.com/gentoo-mirror/guru/blob/master/.github/workflows/pkgcheck.yml). I'm kinda at a loss. Thus, this issue.

Is `pkgcheck scan` even intended to be run locally? Explanatory blog articles are few and far between. Likewise, `man pkgcheck` lacks any examples – like, *any* examples. I'm flying blind in the dark. The occasional flashes of lightning off the starboard wing aren't doing much for my night vision here. :zap: 

Thanks to @radhermit and @mgorny for their tremendous work that I wish I could actually use. Please teach me how to make `pkgcheck` behave itself, sempai.

**Comment by radhermit** [comment]
How are repos configured on your system, i.e. what's ``/etc/portage/repos.conf`` look like? It appears that your local copy of the gentoo repo isn't getting recognized for whatever reason -- pkgcore doesn't have complete compatibility with the portage config, but generally tries to ignore settings it doesn't use.

Running pkgcheck via its github action takes the system configuration out of the equation entirely since it's all handled internally in that case.

**Comment by leycec** [comment]
**Fascinating.** Thanks for the deep dive and prompt attention, radical mountaintop hermit. You're awesome! Let's see if I can't help you help me.

Luckily, I *am* running vanilla Gentoo. Unluckily, I've configured a `/etc/portage/repos.conf/` directory that's probably too complex for its own good rather than just a single `/etc/portage/repos.conf` file. Maybe that's the problem? Here's what I currently see:

```
$ ls -l /etc/portage/repos.conf/
drwxr-xr-x 2 root root 4.0K Jun 16 02:19 .
drwxr-xr-x 9 root root 4.0K Aug  7 00:23 ..
-rw-r--r-- 1 root root  623 May 27 01:13 eselect-repo.conf
-rw-r--r-- 1 root root  762 Sep 16  2019 gentoo.conf
-rw-r--r-- 1 root root 1.5K Jun 16 02:19 local.conf
-rw-r--r-- 1 root root  923 Jan 22  2020 remote.conf
$ cat /etc/portage/repos.conf/gentoo.conf
[DEFAULT]
main-repo = gentoo

[gentoo]
location = /var/db/repos/gentoo
sync-type = git
sync-uri = https://github.com/gentoo-mirror/gentoo.git 
auto-sync = yes
sync-rsync-verify-jobs = 1
sync-rsync-verify-metamanifest = yes
sync-rsync-verify-max-age = 24
sync-openpgp-key-path = /usr/share/openpgp-keys/gentoo-release.asc
sync-openpgp-key-refresh-retry-count = 40
sync-openpgp-key-refresh-retry-overall-timeout = 1200
sync-openpgp-key-refresh-retry-delay-exp-base = 2
sync-openpgp-key-refresh-retry-delay-max = 60
sync-openpgp-key-refresh-retry-delay-mult = 4
```

**Eureka!** That's it:

```
# This line...
location = /var/db/repos/gentoo

# ...should instead look like this.
location = /usr/portage
```

I'd badly misconfigured `/etc/portage/repos.conf/gentoo.conf` all this time, but Portage silently ignored the misconfiguration and overrode that problematic setting with its own correct setting. I never knew anything was amiss because Portage pretended nothing was.

Phew! That's one troubling mystery resolved. `pkgcheck scan` now behaves sanely. `repoman` is not long for this world.

That said, it still might be helpful for `pkgcheck scan` to be a bit more explicit about the exact cause of the failure. Let's save other Gentoo devs from developing a similar head-splitting migraine. Specifically, the fatal error emitted by `pkgcheck scan` on failing to find a local master should probably contain the absolute path of the missing directory: e.g.,

```
$ pkgcheck scan
pkgcheck scan: error: repo init failed: repo 'raiagent' at path
'/home/leycec/tmp/raiagent' has missing masters: 'gentoo'
directory '/var/db/repos/gentoo' not found
```

So, just appending `"directory '{master_dirname}' not found"` to the current error message – or something, something.

Thanks again! All's well that ends with a saner system configuration.

**Comment by radhermit** [comment]
> That said, it still might be helpful for `pkgcheck scan` to be a bit more explicit about the exact cause of the failure. Let's save other Gentoo devs from developing a similar head-splitting migraine. Specifically, the fatal error emitted by `pkgcheck scan` on failing to find a local master should probably contain the absolute path of the missing directory: e.g.,
> 
> ```
> $ pkgcheck scan
> pkgcheck scan: error: repo init failed: repo 'raiagent' at path
> '/home/leycec/tmp/raiagent' has missing masters: 'gentoo'
> directory '/var/db/repos/gentoo' not found
> ```
> 
> So, just appending `"directory '{master_dirname}' not found"` to the current error message – or something, something.

Feel free to open a new issue or PR for this in the pkgcore repo. I've mostly moved on and retired from pkgcore et al., but maybe @mgorny or someone else can look at it.

**Comment by leycec** [comment]
Oh, sure. Thanks again, Tim. Time is scarce for all of us. I appreciate you giving yours. :+1:
