### ISSUE TITLE
pkgcheck scan --commits doesn't seem to catch if a commit summary exceeds 69 characters

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#343]
Per GLEP-66, 
https://www.gentoo.org/glep/glep-0066.html#commit-messages
"The summary line must not exceed 69 characters, and must not be wrapped."

And related, 
"The body should be wrapped at 72 characters."

**Comment by thesamesam** [comment]
We currently check length (InvalidCommitMessage), but we do so _after_ "cat/pkg:", so if the prefix tips us over the edge, we don't notice.

See https://github.com/pkgcore/pkgcheck/blob/e12f045393dfa27b2730caae844f50c38f6afadb/src/pkgcheck/checks/git.py#L560.
