### ISSUE TITLE
Exact(?) matching on BadCommitSummary

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#344]
commit
  BadCommitSummary: commit e371f7d44, summary missing package version '4.7.1': 'net-im/mattermost-desktop-bin: bump to v4.7.1'

[ebuild   R    ] sys-apps/pkgcore-0.12.2::gentoo  USE="-test" PYTHON_TARGETS="python3_10 python3_8 python3_9" 0 KiB
[ebuild   R    ] dev-util/pkgcheck-0.10.4::gentoo  USE="-test" PYTHON_TARGETS="python3_10 python3_8 python3_9" 0 KiB

**Comment by mgorny** [comment]
Yeah, I was planning to look into relaxing this a bit.
