### ISSUE TITLE
Incorrect UnusedInherits (when "conditional"? calls)

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#355]
net-print/cnrdrvcups-lb
  UnusedInherits: version 5.30: unused eclass: autotools
  UnusedInherits: version 5.40: unused eclass: autotools

but they call `eautoreconf` via a function, 
$ grep -r eautoreconf
cnrdrvcups-lb-5.30.ebuild:	common_op eautoreconf
cnrdrvcups-lb-5.30.ebuild:	driver_op eautoreconf
cnrdrvcups-lb-5.40.ebuild:	common_op eautoreconf
cnrdrvcups-lb-5.40.ebuild:	driver_op eautoreconf

# pkgcheck --version
pkgcheck 0.10.8

$ pkgcheck --version
pkgcheck 0.10.7

(happens on both versions, stable and unstable)

**Comment by mgorny** [comment]
Similar problem with pyside2 and virtualx:

```
  UnusedInherits: version 5.15.2-r2: unused eclass: virtualx
```

but:

```
src_test() {
	local -x PYTHONDONTWRITEBYTECODE
	python_foreach_impl virtx cmake_src_test
}
```

**Comment by a17r** [comment]
Same with x11-libs/qscintilla
```
  UnusedInherits: version 2.13.1: unused eclass: qmake-utils
  UnusedInherits: version 2.13.3: unused eclass: qmake-utils
```
uses eqmake5:
```
		run_in_build_dir eqmake5 -recursive ${MY_PN}.pro
```
