### ISSUE TITLE
'unused in master' checks for slaved repos

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#36]
A combination of unused \* check for slaved and master repositories. Report if license/etc. inherited from master is used in slaved repo but not in master, i.e. is likely to be removed.

**Comment by trofi** [comment]
Bumped on it today as well. Example repo: https://github.com/trofi/pkgcore-warts/

pkgcheck flags ::gentoo licenses:
```
$ pkgcheck -r pkgcore-warts -o gentoo
...
unknown
  UnusedLicenses: unused licenses: 0-L, 2dboy-EULA, 3proxy, 3ware, 7plus, 9base, 9wm, ACE, ACML, AFL-2.1, AFL-3.0, AGPL-3, AGPL-3+, AGREP, AIFFWriter.m, ALMWorks-1.2, AMD, AMD-ADL, AMPAS, APL-1.0, APSL-2, ARIADNE, ARM-FAST-MODEL, ASRP, ATOK, AVASYS, AVM-FC, AVM-dtrace, AZARA, Adaptec-EULA, Adobe, ...
```

**Comment by radhermit** [comment]
Fixed in 15c98b6.

**Comment by mgorny** [comment]
Hey, why do you take over my enhancement idea and mix it with some unrelated bug? :-(

**Comment by radhermit** [comment]
Heh sorry, I only was looking at the most recent comment.

**Comment by radhermit** [comment]
I think the initial implementations for all the relevant classes should be done now.
