### ISSUE TITLE
New check: LICENSE doesn't contain variables

### ISSUE THREAD

**Issue by laumann** [pkgcore/pkgcheck#366]
To check for the [new QA policy](https://archives.gentoo.org/gentoo-dev/message/b7764a5112270858ea450ccfa508dc17).

> The only exception [...] is the use of LICENSE itself, i.e. appending is allowed

**Comment by radhermit** [comment]
This should be a one-line change (not including tests).

**Comment by laumann** [comment]
Thanks for the tips @radhermit I'll see about implementing this soon.
