### ISSUE TITLE
Missing "unmatched removal atoms" check

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#369]
repoman would warn about when an unmask is pointless, but pkgcheck doesn't seem to, at least.

Example from `::gentoo`:
```
commit a0b2113bcb53f87ad906a69d3f551922efd5cc81 (HEAD -> master, origin/master, origin/HEAD)
Author: Sam James <sam@gentoo.org>
Date:   Wed May 4 02:20:37 2022 +0100

    profiles/arch/powerpc/ppc64/64le: fix JRE/JDK unmasking

    From repoman (noticed b/c of old CI action);
    ```
    --- Unmatched removal atom(s) in /var/db/repos/gentoo/profiles/arch/powerpc/ppc64/64le/package.mask: -virtual/jre:11, -virtual/jdk:11
    --- Unmatched removal atom(s) in /var/db/repos/gentoo/profiles/arch/powerpc/ppc64/64le/package.mask: -virtual/jre:11, -virtual/jdk:11
    --- Unmatched removal atom(s) in /var/db/repos/gentoo/profiles/arch/powerpc/ppc64/64le/package.mask: -virtual/jre:11, -virtual/jdk:11
    --- Unmatched removal atom(s) in /var/db/repos/gentoo/profiles/arch/powerpc/ppc64/64le/package.mask: -virtual/jre:11, -virtual/jdk:11
    --- Unmatched removal atom(s) in /var/db/repos/gentoo/profiles/arch/powerpc/ppc64/64le/package.mask: -virtual/jre:11, -virtual/jdk:11
    --- Unmatched removal atom(s) in /var/db/repos/gentoo/profiles/arch/powerpc/ppc64/64le/package.mask: -virtual/jre:11, -virtual/jdk:11
    --- Unmatched removal atom(s) in /var/db/repos/gentoo/profiles/arch/powerpc/ppc64/64le/package.mask: -virtual/jre:11, -virtual/jdk:11
    ```

    Fixes: 25ff46699ff036d55928b12d3fe801dc2f83e4b0
    Fixes: ab6527219b01c21eac9f8090959a9c125346c322
    Signed-off-by: Sam James <sam@gentoo.org>
```

Summary:
- In https://github.com/gentoo/gentoo/commit/25ff46699ff036d55928b12d3fe801dc2f83e4b0 and https://github.com/gentoo/gentoo/commit/ab6527219b01c21eac9f8090959a9c125346c322, obsolete masks were dropped.
- This left an unmask which no longer had a mask to reverse:
```
# Sam James <sam@gentoo.org> (2022-01-09)
# No provider (e.g. OpenJDK) available on big endian PPC64 right now
-virtual/jdk:11
-virtual/jre:11
```
- repoman warns on this, pkgcheck doesn't seem to.

It passed CI in https://github.com/gentoo/gentoo/pull/25305 notably. CC @Flowdalic (FYI).

I've noticed a similar issue like this before but I'll file another bug for that.

**Comment by radhermit** [comment]
Just for clarification, this is probably just a bug in UnknownProfilePackage result handling. The code probably doesn't strip optional "-" prefixes before "atomizing" the strings.
