### ISSUE TITLE
Distfile collision check

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#37]
A global check that triggers when multiple packages use distfile with the same name but different checksum, e.g. different URI but same filename.

Implementation notes:
- Abstractly, this probably could be checked per version, though for ebuilds can be optimized to per package.
- Could work in category scope but makes most sense in global.
- Need to cover different sets of digests (i.e. compare only common ones).

**Comment by radhermit** [comment]
How often is this happening right now? Also, is there some reason I can't think of right now why we can't treat distfiles more like a repo and not a flat directory besides historical usage?

I seem to recall various infra discussions or threads, but I'm too lazy to search for them. :smile:

**Comment by mgorny** [comment]
I don't know! That's why we need a check!

**Comment by ferringb** [comment]
Offhand, I'm reasonably sure that the distfiles manager (unless zac rewrote
it and cut over to some emaint implementation) had such a check.  It
shouldn't be possible for it to happen w/ official gentoo mirrors- it just
refuses to mirror, honoring instead the first that it encounters.

That doesn't remove the need for a check, it's just unlikely you'll find
any live examples.

**Comment by radhermit** [comment]
On a further look, it appears this is already covered by the ConflictingChksums keyword but that could probably be improved on in terms of the output reporting at least.

**Comment by radhermit** [comment]
Closing since I think ConflictingChksums covers this request.
