### ISSUE TITLE
Add a commit check that detects removing non-redundant ("last with keyword") versions

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#381]
Let's say I have the following package:

```
Keywords for dev-python/soupsieve:
         |                               |   u   |  
         | a   a     p s     r   a l     |   n   |  
         | m   r h   p p   i i s l o m m | e u s | r
         | d a m p p c a x a s 3 p o 6 i | a s l | e
         | 6 r 6 p p 6 r 8 6 c 9 h n 8 p | p e o | p
         | 4 m 4 a c 4 c 6 4 v 0 a g k s | i d t | o
---------+-------------------------------+-------+-------
   2.3.1 | + + + + + + + + ~ ~ ~ ~ o ~ ~ | 8 o 0 | gentoo
[I]2.3.2 | + + + + + + + + ~ ~ ~ o ~ ~ ~ | 8 o   | gentoo
```

i.e. 2.3.2 doesn't have `~alpha`. Normally, pkgcheck reports:

```
dev-python/soupsieve
  DroppedKeywords: version 2.3.2: alpha, x64-macos
```

However, if I remove the old version and commit, the package passes cleanly. I think it'd be useful if pkgcheck detected that last version having some keyword was removed, and warned about that.

**Comment by arthurzam** [comment]
I'm reopening so we don't miss it.

> 
> <@mgorny> arthurzam: was 0.10.11 supposed to start reporting that i've removed the last stable version? because fwics it doesn't, so i'm not sure if my bug was closed as accident or not

I have taken `dev-python/cryptography` as an example where we can break things.
```bash
$ rm dev-python/cryptography/cryptography-3.4.7-r3.ebuild
$ pkgcheck --version
pkgcheck 0.10.11-12-gc2761ba -- Thu, 26 May 2022 21:11:57 +0300
$ pkgdev commit -as # everything works [1]
$ pkgcheck scan --commits
dev-python/cryptography
  DroppedStableKeywords: commit 93ec54ecbb (or later) dropped stable keywords: [ amd64, arm, arm64, hppa, ppc, ppc64, sparc, x86 ]
  DroppedUnstableKeywords: commit 93ec54ecbb (or later) dropped unstable keywords: [ ~alpha, ~ia64, ~loong, ~m68k, ~mips, ~s390, ~ppc-macos, ~x64-macos, ~sparc-solaris, ~sparc64-solaris, ~x64-solaris, ~x86-solaris ]
```

Normal pkgcheck scan can't know what broke in the staged area compared to before the commit. For this we need `--commits` mode. After the fix, it looks like it works currently.

@mgorny what are your thoughts.

**Comment by mgorny** [comment]
Well, it doesn't work with 0.10.11 release but it does from git master, so I guess it'll work in the next release ;-).

That said, I'm not convinced about the classification right now. I mean, dropping both stable and ~arch keywords should have the same severity IMO, maybe only lesser if we're dealing with exp arches.

**Comment by arthurzam** [comment]
I prefer if it was an `Error` level for all arches, both for stable and keyword. A warning for exp arches might be too easily lost in my opinion. What do you think?

If someone wants to force drop it, he can just skip the commits QA check (for example using `git push --signed` instead of `pkgdev push`).

**Comment by thesamesam** [comment]
Agreed this is serious. Remember, devmanual (and in general) we say we should avoid downgrades for users whenever possible. So let's make it an error.

**Comment by mgorny** [comment]
Sure, error works for me.
