### ISSUE TITLE
Detect pure-DEPEND weak blockers (!)

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#399]
Example: https://github.com/gentoo/gentoo/commit/6b2955f24cb027e3aa10e6dfde91d792a4b08a5c.

Pure-DEPEND weak blockers (!) don't work as they control whether we ignore file collisions at the point of merge - hence they belong in RDEPEND. It's fine but not necessary for them to be in both DEPEND and RDEPEND.

Such cases should be changed to RDEPEND or RDEPEND +DEPEND (same effect as just RDEPEND)

**Comment by arthurzam** [comment]
OK, so just to check I understand correctly:

Usage of Pure-DEPEND weak blockers (those that use single `!`) in those types:

1. RDEPEND - fine and the correct place
2. (BDEPEND or DEPEND) but not in RDEPEND - wrong (most likely mistake) and should show a warning, or even error? (after gentoo tree is fixed)
3. (BDEPEND or DEPEND) but also in RDEPEND - wrong, should show warning that it is useless in first group
4. IDEPEND - I think fine, but really not sure...
