### ISSUE TITLE
check for suspect RESTRICT="mirror" or RESTRICT="fetch"

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [pkgcore/pkgcheck#407]
If a distfile has only free licenses it should not be mirror/fetch restricted

**Comment by mgorny** [comment]
I think people may be also restricting mirroring to avoid hitting mirrors with huge flles,

**Comment by ajakk** [comment]
Such a check also wouldn't make sense in overlays where it's unlikely anything is mirrored.

**Comment by Alessandro-Barbieri** [comment]
> I think people may be also restricting mirroring to avoid hitting mirrors with huge flles,

From https://devmanual.gentoo.org/general-concepts/mirrors/
```
The RESTRICT="mirror" setting should be used if we cannot legally mirror certain files; files will still be downloaded from the original locations.

There is also RESTRICT="fetch", which prevents Portage from trying to fetch anything manually. [...] This should only be used if a license requires it.
```
here it only list legal reason to use `RESTRICT`

**Comment by arthurzam** [comment]
I suspect it would be very hard and even impossible to define correct logic for this check, even if limited to gentoo repo only.
