### ISSUE TITLE
autoupdate ebuild header

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [pkgcore/pkgcheck#409]
This is a regression from repoman
Repoman automagically fixed the ebuild header, fixing the copyright year and adding "Gentoo Authors" when necessary

**Comment by thesamesam** [comment]
`pkgdev commit` from `pkgdev` does this. It's not for `pkgcheck`.

**Comment by Alessandro-Barbieri** [comment]
> `pkgdev commit` from `pkgdev` does this.
I've just tried (0.2.1-r1) and it doesn't work

**Comment by thesamesam** [comment]
Then you should file a bug in the `pkgdev` repository with an attachment of a bad ebuild and include all the commands you ran.
