### ISSUE TITLE
Warn if IUSE=ipv6 exists and adds no dependencies

### ISSUE THREAD

**Issue by mattst88** [pkgcore/pkgcheck#414]
`IUSE=ipv6` often exists but adds no dependencies. Many packages don't have an ipv6 enable/disable option. There's almost never any value in disabling ipv6 support, and if a user wishes to they should just disable it in the kernel which... actually disables ipv6 instead of trying to disable it in a mishmash of packages.

We should warn if a package has `IUSE=ipv6` that doesn't add any dependencies. Maybe we could go for a super simple warning that complains if `ipv6` isn't described in metadata.xml.

**Comment by arthurzam** [comment]
Got approval from QA team for this check.
For now this will be check only on Gentoo main tree (to avoid flagging for overlays, user repos, etc)

Logic:
`IUSE=ipv6` and no effect on any dependencies (not as transitive use flag like `[ipv6=]`, and not as conditional like `ipv6? ( ... )`)

**Comment by kuraga** [comment]
https://www.mail-archive.com/gentoo-dev@lists.gentoo.org/msg98876.html
