### ISSUE TITLE
Emacs integration

### ISSUE THREAD

**Issue by xgqt** [pkgcore/pkgcheck#417]
Hello!

I opened this issue to discuss possibilities of pkgcheck integration into GNU Emacs editing workflow.

For few past months I have been trying to write a plugin for flycheck, a on-the-fly checker (https://github.com/flycheck/flycheck) and finally found a way to integrate the components.

# Flycheck-Pkgcheck

## Code

The current state of flycheck-pkgcheck is as follows:
```lisp
(require 'flycheck)


(flycheck-define-checker pkgcheck
  "A checker for ebuild files."
  :modes 'ebuild-mode
  :predicate (lambda () (buffer-file-name))
  :command ("pkgcheck"
            "scan"
            "--exit="
            "--format={package}-{version}.ebuild:0:{level}:{name}: {desc}"
            "--reporter=FormatReporter"
            "--verbose"
            (eval (buffer-file-name)))
  :error-patterns
  ((info
    line-start (file-name) ":" line ":" "info" ":" (message) line-end)
   (info
    line-start (file-name) ":" line ":" "style" ":" (message) line-end)
   (warning
    line-start (file-name) ":" line ":" "warning" ":" (message) line-end)
   (error
    line-start (file-name) ":" line ":" "error" ":" (message) line-end)))


;;;###autoload
(defun flycheck-pkgcheck-setup ()
  "Flycheck pkgcheck setup."
  (interactive)
  (add-to-list 'flycheck-checkers 'pkgcheck t))

;;;###autoload
(add-hook 'ebuild-mode-hook 'flycheck-pkgcheck-setup)


(provide 'flycheck-pkgcheck)
```
It can be also found under this link: https://dev.gentoo.org/~xgqt/scripts/flycheck-pkgcheck.el

## Showcase

![2022 07 25_08:25:16](https://user-images.githubusercontent.com/47485207/180711859-1700ffe8-8e46-4303-8759-6523e03b91d3.png)

# Questions

## lineno alternative

There are a few hacks in `flycheck-pkgcheck` code, most importantly flycheck requires that the offending line is reported with `line`, so I had to hardcode line 0 (`....ebuild:0:{level}...`).

So, a thing to consider in pkgcheck format API: There is `lineo` but it is not guaranteed that it will return a line number, maybe an new keyword could be added to return `lineno` or `0` (eg. `lineno0`)?

## Hosting

Would pkgcheck take this code if I were to open a pull request?

**Comment by arthurzam** [comment]
Thanks for the work.

About including `flycheck-pkgcheck` in pkgcheck - I will gladly include it (inside `contrib/` in repo I guess).
Also, where should it be installed by ebuild, and do you want behind some USE flag (maybe `emacs`) - but please also write the description for it if the default one isn't good enough 😃 

About including `lineno0`, I don't like it. This is a "weird" var that will be somewhat hard to explain in docs. But there is a much better and cleaner solution, add new reporter. Let's call it `FlycheckReporter`, write all logic inside python code (you can do much better work there, which will be even better customized for flycheck). Easier to maintain, read and write.
For that, I will create first draft in near week, create PR, and ping you so you can check the integration.

**Comment by xgqt** [comment]
Thanks @arthurzam !

> Also, where should it be installed by ebuild

I would make a PR for change of pkgcheck ebuild when Emacs support is merged in; it is not like sytemd units, because ELisp code should be compiled and should have a (lets call it, for the sake of simplicity) "loader" file that loads necessary function and hooks for setup inside Emacs.
So, yes, a `IUSE="emacs"` will be necessary.
USE="emacs" is global and it is good enough.
Examples:
- https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-util/cmake/cmake-3.23.3.ebuild
- https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-scheme/gambit/gambit-4.9.4-r1.ebuild|

> add new reporter. Let's call it FlycheckReporte

Good idea.

**Comment by arthurzam** [comment]
Hey, I added the reporter at branch [emacs-flycheck](https://github.com/pkgcore/pkgcheck/tree/emacs-flycheck).
Please open a branch from that branch, use the reporter (for example `pkgcheck scan --exit= --reporter=FlycheckReprter --verbose`), and add the lisp integration into `contrib`, and then open a PR to master (so it includes my commit).

Of course, we can improve the logic behind the output, and customize it as you need (just say what you need). Also, I may recommend to look at [scopes](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#check-selection), as maybe package or git results are irrelevant?

**Comment by xgqt** [comment]
Looks like it's working.

![image](https://user-images.githubusercontent.com/47485207/182046530-f2f1ccad-2a5a-4e0a-ac96-eb3cd5e18650.png)

**Comment by arthurzam** [comment]
Closing as done by that PR
