### ISSUE TITLE
"BadCommitSummary" version check should be ignored for acct-* packages

### ISSUE THREAD

**Issue by juippis** [pkgcore/pkgcheck#433]
```
  BadCommitSummary: commit ae8f0e4e8b2, summary missing package version '0': 
  'acct-user/goaccess: add user for goaccess'
```
Could probably be extended to virtuals.

**Comment by arthurzam** [comment]
OK, first implementation was done, and it was quite simple

For now I did for `acct-*` categories, as looking for `git log virtual/` shows that most do use the version there?
Of course I can add an exception for it too, just want an ACK from devs/QA for it 😄
