### ISSUE TITLE
Add flag to control stable `pkgcheck scan`'s `StableRequest` day limit

### ISSUE THREAD

**Issue by mattst88** [pkgcore/pkgcheck#444]
`projg2/mgorny-dev-scripts` includes a script I wrote that uses pkgcheck to produce a table of package stabilization candidates.

E.g. today:

````sh
gentoo % stablereq-find-candidates x11@gentoo.org
 days │ category/package:slot
──────┼────────────────────────────────────────────────────────────────────────
   40 │ dev-libs/libevdev-1.13.0:0
   28 │ media-libs/mesa-22.1.7:0
   53 │ virtual/opencl-3-r2:0
   49 │ x11-drivers/xf86-video-nv-2.1.22:0
````
In https://github.com/projg2/mgorny-dev-scripts/pull/7#issuecomment-1083993694 I commented:

> I would really like to add something similar to imlate's --mtime=... option that lets you pick a number of days in-tree rather than using pkgcheck's hard-coded 30 day stabilization limit.
> 
> Is there any precedent for pkgcheck taking arguments like pkgcheck scan -k StableRequest=15 or something like that?

It would be nice to have something like this in `pkgcheck` so I can use it in `stablereq-find-candidates`.

**Comment by thesamesam** [comment]
Good news! @EmRowlands implemented https://github.com/pkgcore/pkgcheck/pull/429.

**Comment by mattst88** [comment]
\o/
