### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mrueg** [pkgcore/pkgcheck#49]
@radhermit if possible, can you cut a new pkgcheck release? Thanks!

**Comment by radhermit** [comment]
Just to note, this requires new snakeoil and pkgcore releases which both are waiting for me to fix/merge a few things so it might take a week or so.

**Comment by mrueg** [comment]
@radhermit thanks for your quick reply. Out of curiousity, what needs to be done for a new release in snakeoil and pkgcore?

**Comment by radhermit** [comment]
Technically nothing anymore, but I'd like to add support for automatically uploading dist files and wheels to pypi/github via travis-ci so I have slightly less to manually do in the future. :smile:

**Comment by mrueg** [comment]
How about doing this one release manually and then work on automating it? ;-)

**Comment by radhermit** [comment]
Releases for snakeoil, pychroot, pkgcore, and pkgcheck are now all out on pypi (tarballs and wheels) and in the gentoo repo.
