### ISSUE TITLE
Add commit check for SRC_URI URL changing without new distfile name

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#493]
pkgcheck could warn if we know SRC_URI has changed with the distfile name remaining the same (no rename or same rename as before) if SRC_URI has changed between two patterns we know should emit different artifacts.

Example would be something like changing from a github-generated tarball for a tag -> a release tarball (https://bugs.gentoo.org/881239):

```
# These two have the same distfile name (and hence won't retrigger mirroring) but shouldn't be the same in content!
-SRC_URI="https://github.com/wojtekka/${PN}/archive/${PV}.tar.gz"
+SRC_URI="https://github.com/wojtekka/${PN}/releases/download/${PV}/${P}.tar.gz"
```

We know the automated github tag tarball can't be the same as one manually uploaded (or even generated by an action), so a rename is necessary.

cc @zougloub

**Comment by thesamesam** [comment]
Further (and I don't know if this is practical), we could try to fetch the old SRC_URI and new and compare checksums, but I doubt that's worth it. I guess we could go off if the Manifest changes, but then we're missing cases where someone updates SRC_URI but forgets to wipe the distfile locally so doesn't test the new one (been there myself in my early days!).

**Comment by zougloub** [comment]
Got another kind of collision in sci-geosciences/viking documentation (patch in 
https://github.com/gentoo/gentoo/pull/28247/commits/1a433c16792c48db110aba9733e5847b7bff856c).

I think a natural approach would be for a tool to re-download the distfile whenever the URL has changed,
also making sure that all package versions distfiles of same name are from the same URL. But that doesn't sound easy.

Reading the ebuilds we get `(URL, distfile)` pairs and from the old manifest we have a `(distfile, checksum)` list; if an ebuild is added/modified/renamed we get a new set of candidate `(URL, distfile)` pairs, and we can resolve `(distfile, checksum)` for the new URLs. We'd need to compare the old state (from SCM) and new state (form working directory) to find collisions.

**Comment by zougloub** [comment]
Got another collision in dev-python/rpyc-5.2.3 ; at some point the ebuild switched from using github releases to pypi releases, which don't contain the same data.
Gentoo mirrors still have the data from the github release.
For some reason the pypi archive has timestamps in 2020, whereas the 5.2.3 release is from 2022-08-04...

**Comment by thesamesam** [comment]
> Got another collision in dev-python/rpyc-5.2.3 ; at some point the ebuild switched from using github releases to pypi releases, which don't contain the same data. Gentoo mirrors still have the data from the github release. For some reason the pypi archive has timestamps in 2020, whereas the 5.2.3 release is from 2022-08-04...

We actually cover this subset of cases nowadays already with PythonGHDistfileSuffixCheck (https://github.com/pkgcore/pkgcheck/issues/382) because it was so common to have to change for e.g. tests.
