### ISSUE TITLE
Warn on no-revbump for PEP517

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#498]
Enabling PEP517 mode is a non-conservative change and may result in installed files changing. It should always be done in a new revision.

**Comment by thesamesam** [comment]
We need to handle this before too much of the tree is converted to PEP517, as it'll stop being useful then.

**Comment by arthurzam** [comment]
Currently the issue is that in the git checks, we use the not-parsed ebuilds, which results in my inability to know the state of PEP517. This is the reason for it being postponed.

**Comment by thesamesam** [comment]
I think we can do it with reduced accuracy if we regex-match the text (like we do for the copyright check) but I'm not sure how to get the old ebuild text.

**Comment by arthurzam** [comment]
> but I'm not sure how to get the old ebuild text.

https://github.com/pkgcore/pkgcheck/blob/861c24ab76bfc36de2ca80a8375866e4123dc51a/src/pkgcheck/checks/git.py#L364-L376
