### ISSUE TITLE
Add a check for hashed pypi URLs

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#505]
E.g.:

```
SRC_URI="https://files.pythonhosted.org/packages/8a/a9/d95bc3268e21b460639806ccb48a5a95526c6018862f1aa852c69bce8f1d/${P}.tar.gz"
```

Given proper fetching for them is a kind of secret knowledge, I suppose pkgcheck could suggest using `https://files.pythonhosted.org/packages/source/${PN::1}/${PN}/${P}.tar.gz` instead. However, since that involves this "first letter", "package name" thing, perhaps it should just print this specific URL as an example rather than trying to figure out something to match the original.

**Comment by thesamesam** [comment]
Maybe distutils-r1 should just default to it like ruby-fakegem.eclass does.

**Comment by mgorny** [comment]
This one's covered by pypi.eclass check already.
