### ISSUE TITLE
Check for deprecated hashes

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#508]
I suppose it wouldn't harm to check for deprecated Manifest hashes. The set I have in mind right now is `MD5`, `SHA1`, `RMD160`, `WHIRLPOOL`. Probably makes sense both as repo-wide check for `manifest-hashes` and per-Manifest check.

**Comment by thesamesam** [comment]
Portage side: https://bugs.gentoo.org/888884
