### ISSUE TITLE
Add check to warning if certain known unstable URLs are used in SRC_URI

### ISSUE THREAD

**Issue by Flowdalic** [pkgcore/pkgcheck#510]
If an known unstable URL is used in SRC_URI, then pkgcheck should emit a warning. Typical examples are `.patch` URLs of pull requests, as the content of the patch may change if new commits are added to the pull request, of if the pull request is force pushed.

While is is often not an immediate problem in ::gentoo, as the mirrors will keep the distfile stable, it is an issue in overlays and should be generally avoided. Hence I would always warn if unstable URLs are used.

See https://github.com/gentoo/guru/commit/d077f2262c1423afe2b1a266469237e0cc18fcd6#r94795358 for an example.

**Comment by mgorny** [comment]
Perhaps we should add a global list of bad URLs, including pypi hashed URLs (#505) and `githubusercontent.com` domain (noticed in #514).
