### ISSUE TITLE
Help is not precise: comma-separated list arguments

### ISSUE THREAD

**Issue by kuraga** [pkgcore/pkgcheck#520]
Good day!

```bash
pkgcheck scan --help
```
```
<...>
  -C CHECKSET[,-CHECKSET,...], --checksets CHECKSET[,-CHECKSET,...]
                        scan using a configured set of check/keyword args
  -s SCOPE, --scopes SCOPE
                        limit checks to run by scope
  -c CHECK, --checks CHECK
                        limit checks to run
  -k KEYWORD, --keywords KEYWORD
                        limit keywords to scan for
<...>
```

But `--scopes`, `--checks`, `--keywords` keys also receive a comma-separated list as an argument.

(Potentially, there are such issues at other places.)

Thanks!

**Comment by kuraga** [comment]
@arthurzam , thanks!

P.S. Sorry, how has it been fixed? Have you declared them as "delayed actions"? :smile:

**Comment by kuraga** [comment]
@arthurzam , thanks!

P.S. Sorry, how has it been fixed? Are all of them "delayed actions" and have you change how delayed actions' help is handled? Is `--checksets` something else? :smile:

**Comment by arthurzam** [comment]
> P.S. Sorry, how has it been fixed? Are all of them "delayed actions" and have you change how delayed actions' help is handled? Is `--checksets` something else? smile

Yes, they were all of delayed action, and the help/doc formatting was very bad for them. By changing it to check the delayed "inner" type, I get much better help message (notice the `+` and `-` added where appropriate). `--checksets` was just not delayed.

```
check selection:
  --net                 enable checks that require network access
  -C CHECKSET[,-CHECKSET,...], --checksets CHECKSET[,-CHECKSET,...]
                        scan using a configured set of check/keyword args
  -s SCOPE[,-SCOPE,...], --scopes SCOPE[,-SCOPE,...]
                        limit checks to run by scope
  -c CHECK[,-CHECK,+CHECK...], --checks CHECK[,-CHECK,+CHECK...]
                        limit checks to run
  -k KEYWORD[,-KEYWORD,...], --keywords KEYWORD[,-KEYWORD,...]
                        limit keywords to scan for
```

This fix is in snakeoil dependency, and I hope to release a new version very soon to include this fix.
