### ISSUE TITLE
Improve FormatReporter documentation

### ISSUE THREAD

**Issue by kuraga** [pkgcore/pkgcheck#522]
Good day!

Propose to improve `FormatReporter` documentation.

First, it [doesn't refer to `--format` option](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#formatreporter).

(And it's possible other "subjects" don't refer their options.)

Second, we have
```
--format FORMAT_STR
Custom format string used to format output by FormatReporter.
Supports python format string syntax where result object attribute names surrounded by curly braces are replaced with their values (if they exist).
```
But these `result object attribute names` are nor listed nor documented. Propose to do that.

Thanks!

**Comment by arthurzam** [comment]
I agree about improving `FormatReporter` docs to include a reference.

And about the `--format` full options list, you can see the shared one [here](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#reporter-options) or in man page or in `--help` view.
And about all other options, I can't list them all, as this depends on each result.

**Comment by kuraga** [comment]
Thanks!

What about each result's documentation improving to reflect attributes? :)
