### ISSUE TITLE
Stable sort order for reports

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#53]
Would be nice if pkgcheck sorted the output using some stable key. See e.g. https://gitweb.gentoo.org/report/gentoo-ci.git/commit/?id=cffb12f31bef7cdff1e71dba6acdfc41fd083167

**Comment by radhermit** [comment]
Once parallelism is added internally (#27) I don't think it will be easy to efficiently sort output during a scanning run.

Therefore, I think this should be done externally post-run if support is added to reload output files of certain types, e.g. xml/json. Probably could add a tool/script to the repo that helps with munging and extracting data from those types of files.

**Comment by radhermit** [comment]
Now results should be sorted properly per pkg, but pkg to pkg results will not be sorted when running concurrently. I'm not sure that's worthwhile, but I guess we could look into how much memory is needed for buffering check results during certain pkg check lags.

**Comment by radhermit** [comment]
Closing this since reports should be sorted properly when run serially now. If someone really wants proper sorting when running checks concurrently they can open a new issue and argue for why they can't use post processing to sort checks.
