### ISSUE TITLE
Warn on semi-reserved variable names (single-letter uppercase variables and [A-z]DEPEND) in global scope

### ISSUE THREAD

**Issue by thesamesam** [pkgcore/pkgcheck#536]
1. Ebuilds should avoid using single-letter uppercase variables in global scope like `H` because they're semi-reserved and may conflict with future EAPI definitions (we already have `A`, `S`, etc). It's also not very descriptive.
2. Ditto for `[A-z]DEPEND` (e.g. `HDEPEND`). For these, we could suggest H_DEPEND instead (underscorify the bad var), but that's still not great.

I think the check should be a warning with the message "Uses semi-reserved name likely to clash with future EAPIs."

**Comment by xgqt** [comment]
> Ditto for [A-z]DEPEND (e.g. HDEPEND). For these, we could suggest H_DEPEND instead (underscorify the bad var), but that's still not great.

If a "weird" `*DEPEND` is used I think pkgcheck should suggest "try introducing COMMON_DEPEND" as it is common practice to put shared DEPENDencies there, though that might not fit with dev's intention.
