### ISSUE TITLE
NonsolvableDeps output strips subslot making errors look wrong

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#56]
https://qa-reports.gentoo.org/output/gentoo-ci/887dce149/output.html#app-emulation/vmware-player

> NonsolvableDeps	nonsolvable depset(rdepends) keyword(~amd64) profile (default/linux/amd64/13.0): solutions: [ dev-libs/nettle:0 ]

while the ebuild actually states `dev-libs/nettle:0/6` which explains why it fails.

**Comment by radhermit** [comment]
Should be fixed via https://github.com/pkgcore/pkgcore/commit/b2a39ac2bcf054ff84a8a1697a96bcfe3c6bd61a.
