### ISSUE TITLE
pkgcheck checks all if a category doesn't exist (in profiles/category)

### ISSUE THREAD

**Issue by mm1ke** [pkgcore/pkgcheck#564]
Hi,

I've came across this on the guru overlay.
I'm using pkgcheck to daily check the packages in the guru overlay. Some days ago pkgcheck had a spike from ~300 to ~700 issues on this overlay. This didn't looked normal to me so i've checked what was going on.
It happened because packages residing in `dev-raku` trigger pkgcheck to check everything. Turns out, on the guru overlay packages were added to this category some days ago but the category wasn't added to `profiles/category`.  (should be fixed with: [9b1c252ed9ef70dd8f82c87cbdc1b29c0c5cafb](https://github.com/gentoo/guru/commit/19b1c252ed9ef70dd8f82c87cbdc1b29c0c5cafb) )
I'm wondering if `pkgcheck` should check for this beforehand but i guess the acutal behaviour is non ideal.

**Comment by arthurzam** [comment]
Seems like the check `RepoProfilesCheck` with the result `UnknownCategoryDirs` wasn't triggered since it was enabled only for gentoo main repo. While currently being just a warning and not an error, so it could be missed, for now I think just enabling it for most repos is the correct behavior.
