### ISSUE TITLE
Exclude @USER_VARIABLEs from MissingInherits

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#575]
```
dev-util/spirv-llvm-translator
  UnstableOnly: for arch: [ x86 ], all versions are unstable: [ 15.0.0, 16.0.0 ]
  PotentialStable: version 15.0.0: slot(15), stabled arch: [ amd64 ], potential: [ ~x86 ]
  DroppedKeywords: version 16.0.0: riscv
  MissingInherits: version 16.0.0: llvm.org: missing inherit usage: 'LIT_JOBS', line 58
```

`LIT_JOBS` is a `@USER_VARIABLE`, so I don't think it needs to be pinned to any specific eclass. In this particular case, the ebuild is using it for consistency but has no reason to inherit (quite intrusive) `llvm.org.eclass`.

I think it'd be reasonable to exclude `@USER_VARIABLE`s from this check. WDYT?

**Comment by mgorny** [comment]
Alternatively, I suppose we could create a small `lit.eclass` to streamline this — if I think about it more, perhaps that'd make more sense, even if it'd be used only by `llvm.org.eclass` and `spirv-llvm-translator`.

**Comment by thesamesam** [comment]
Given e.g. https://xgqt.gitlab.io/blog/posts/2023/02/24/ebuild-lit-tests/ (cc @xgqt), I'd prefer an eclass for this instead. I think it's confusing and it might mask real issues if we ignore user variables for this.

**Comment by xgqt** [comment]
Indeed, new eclass would be useful.
