### ISSUE TITLE
cargo.eclass checks: detect unnecessary `$(cargo_crate_uris)` and `CRATES` with `-` separator

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#586]
Given the new optimizations, pkgcheck could report:

1. `CRATES` using `-` instead of `@`.
2. `$(cargo_crate_uris)` and `$(cargo_crate_uris ${CRATES})` being called directly, instead of `${CARGO_CRATE_URIS}`. Note that calling it with different arguments is still valid.

**Comment by mgorny** [comment]
CC @gentoo/rust

**Comment by mgorny** [comment]
CC @ionenwks, @thesamesam

**Comment by arthurzam** [comment]
@mgorny It would help me if you could give some more info, as in the [wiki](https://wiki.gentoo.org/wiki/Project:PkgCore#New_QA_check) (Yes, I know I should create GitHub issues templates for those, TODO...)

I'm not that familiar with rust ebuilds, so having those will make it easier for me :)

**Comment by mgorny** [comment]
Roughly:
- https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=0e0a59b931d9d079aca1347015c122bdc2fb7f58
- https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=21595fc8da27066eb90b11c2c6e24c7a43015641

1. If `CRATES` contains at least one token that doesn't contain `@`, output a warning: `using - as name-version separator in CRATES is suboptimal, use name@version instead`. Detailed help may suggest using pycargoebuild 0.7+ to generate new CRATES.
2. If `$(cargo_crate_uris)`, `$(cargo_crate_uris ${CRATES})` or another variant of the latter with/out quoting and with/out `{}`s is found, output a warning: calling `$(cargo_crate_uris) is suboptimal, use ${CARGO_CRATE_URIS} for global CRATES instead`.
