### ISSUE TITLE
Warn if ebuild is changed but old PYTHON_COMPAT are left

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#591]
Not a high priority but I think it'd make sense to emit a warning if someone changes an ebuild but doesn't remove old Python implementations from `PYTHON_COMPAT`. Something in a manner similar to how we do `RdependChange`, i.e. one time warning when checking commits.

**Comment by thesamesam** [comment]
I've dropped the old way of doing this from the eclass given it was UB: https://github.com/gentoo/gentoo/commit/94e8e20b0fcbb930494c218faca39e84c6035bd6.
