### ISSUE TITLE
Feature request, new check: Perl virtual dependencies

### ISSUE THREAD

**Issue by akhuettel** [pkgcore/pkgcheck#593]
Here's a wish for a new check. (@thesamesam @arthurzam)

- If PN is dev-lang/perl or perl-core/* or virtual/perl-*, skip the check
- Otherwise, all dependency declarations that specify a Perl virtual (virtual/perl-*) and do **not** give any type of version dependency trigger a warning.

Example: [dev-perl/XXX-0.380.0](https://github.com/gentoo/gentoo/blob/66ebb42027c1b2cd505e648ffc90f1bcac8f2855/dev-perl/XXX/XXX-0.380.0.ebuild#L17-L19)
```
BDEPEND="${RDEPEND}
        virtual/perl-ExtUtils-MakeMaker
"
```
Triggers a warning since the dependency on virtual/perl-ExtUtils-MakeMaker in BDEPEND does not specify any version (i.e., no =, <, >, ~, ...)

If this ever goes into CI, all current warnings will have to be grandfathered in since otherwise things explode.

**Comment by thesamesam** [comment]
We can use the implementation of `MissingPackageRevision` for some inspiration, maybe

**Comment by arthurzam** [comment]
1. Is it relevant only to ebuilds inheriting perl eclass, or all packages?
2. Thank for the precise logic, but what is the issue that requires this? I need this for the documentation and explanation :)

**Comment by akhuettel** [comment]
>     1. Is it relevant only to ebuilds inheriting perl eclass, or all packages?

All packages

>     2. Thank for the precise logic, but what is the issue that requires this? I need this for the documentation and explanation :)

The virtuals stand for packages that have releases both as part of dev-lang/perl and standalone. Apart from rare special cases, if you require "any" version of such a virtual, this will always be fulfilled by dev-lang/perl.

For a long time we had the policy that also version-less dependencies on Perl virtuals should be added to packages. I want to change that, since these dependencies are pointless and obscure which virtuals are still needed. Reducing the number of Perl virtuals would be great, and once we have only version dependencies in the tree it's trivial to see which ones are obsolete and which ones not.
