### ISSUE TITLE
[Bug]: Typo in WhitespaceFound report

### ISSUE THREAD

**Issue by leio** [pkgcore/pkgcheck#633]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`pkgcheck scan` and co report:
```
  WhitespaceFound: version 44.2-r1: ebuild has leading whitespace on on lines: 109, 110, 112
```

There is an extra `on`.

### Expected Behavior

```
  WhitespaceFound: version 44.2-r1: ebuild has leading whitespace on lines: 109, 110, 112
```

### pkgcheck version

pkgcheck 0.10.26

### pkgcore version

pkgcore 0.12.23

**Comment by arthurzam** [comment]
Thank you for finding it
