### ISSUE TITLE
don't mislead users about updating the Manifest

### ISSUE THREAD

**Issue by semenzato** [pkgcore/pkgcheck#635]
Executing `ebuild <path-to-ebuild> manifest` produces this output:
```
>>> Creating Manifest for <path-to-ebuild-dir>...
```
even when the program is not actually updating the Manifest because the basename of the SRC_URI has not changed.  It would be helpful to output a warning in addition to, or instead of that message.

It would be even nicer if Portage allowed a relative pathname in the Manifest file instead of just the basename.  This (superficially) seems doable without breaking backward compatibility.  It would simplify some automated builds for which it is easier to put a version number somewhere in the path rather than in the basename, and allow a better organization of archive files in a server.

Related bug: https://github.com/pkgcore/pkgcheck/issues/493

Thanks!

**Comment by arthurzam** [comment]
Most of the conversation occurred at: https://bugs.gentoo.org/917649

This isn't a bug in pkgcheck. Maybe in portage (I don't think so) and maybe we can improve somewhere the verbosity of pkgdev, but once again, not pkgcheck.

If you disagree with me closing the issue, feel free to add info & context and reopen the issue 😄
