### ISSUE TITLE
Promote `PkgBadlyFormedXml` from Warning to Error

### ISSUE THREAD

**Issue by APN-Pucky** [pkgcore/pkgcheck#668]
`::sci` runs `pkgcheck scan` in it's CI, but since this is only a warning the CI does not fail.
I think requiring `metadata.xml` to be a correctly formatted is reasonable and `PkgBadlyFormedXml` should be treated as an error.

The QA CI https://bugs.gentoo.org/922385 reports this as a failure, so it should be an error here too.

Since this did go unnoticed in `::sci` it has been dropped from repology (See https://github.com/repology/repology-updater/commit/688fc91d1092e3c7b7b5c79bd03935bb54e872b1).

Cross-reference: https://github.com/gentoo/sci/pull/1252

**Comment by arthurzam** [comment]
After some more checks, I see no issue with upgrading it to error. I'm more surprised it was a warning before.
