### ISSUE TITLE
[Bug]: sudden error: repos.conf: default repo 'gentoo' is undefined or invalid

### ISSUE THREAD

**Issue by NHOrus** [pkgcore/pkgcheck#686]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

While working in clone of git "gentoo" repository located well outside /var/db/repos, every inocation of pkgcheck ends with message `error: repos.conf: default repo 'gentoo' is undefined or invalid` instead of doing anything at all.

### Expected Behavior

pkgcheck and pkgdev to work normally, like they did three weeks ago.
My workflow involves mounting clone of git repository inside different containers and working with copy on host, including pkgdev/pkgcheck invocations.

### pkgcheck version

pkgcheck 0.10.30

### pkgcore version

pkgcore 0.12.27

**Comment by NHOrus** [comment]
This may be a bug in stage3 instead.

**Comment by arthurzam** [comment]
I suspect "/etc/portage/repos.conf/" wasn't configured correctly, or pointing to non existing repo. pkgcheck requires correctly configured repos & stuff to work.
