### ISSUE TITLE
Check for missynced virtual/* keywords

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#69]
Normally, a keywords in `virtual/*` should be be pretty much union of keywords of all packages satisfying the virtual. I think it would be nice to have a check for virtuals with keywords mis-synced to their packages.

**Comment by radhermit** [comment]
Initial implementation now in git. Note that it appears to mostly catch dev/prefix keywords and virtuals with deps missing due to avoiding circular deps.
