### ISSUE TITLE
NonsolvableDeps fails with USE-opposite dep&blocker

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#76]
After upgrading to the fresh snapshot, I get a lot of NonsolvableDeps due to packages having `a? ( x ) !a? ( !x )` deps. I think this was resolved in the past, so the py3 refactoring must have reintroduced it.

https://qa-reports.gentoo.org/output/gentoo-ci/957200b/output.html

**Comment by radhermit** [comment]
Unless I'm remembering incorrectly, this wasn't ever resolved yet. It was introduced during some additional dep visibility scanning/error handling work that the CI checks probably don't include yet.

**Comment by mgorny** [comment]
Oh.That's a total (and only) broken for CI pkgcheck upgrade. Any chance you could find a cheap hack around it, or possibly some reverting patch I could use?

**Comment by mgorny** [comment]
s/broken/blocker/

**Comment by mgorny** [comment]
Thanks, it looks good now! Let's try again.
