### ISSUE TITLE
Add a check for local USE_EXPAND flags not defined in profiles/desc

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#79]
Alike https://bugs.gentoo.org/583770.

If `FOO` is in USE_EXPAND, then all `foo_*` IUSE defined in package must be present in profiles/desc. In other words, detect that packages don't attempt to locally extend USE_EXPAND.

**Comment by radhermit** [comment]
This has existed for a while in the form of of the ProbableUSE_EXPAND keyword (608c699178638ff1db0814fb5856c33e583ca337).

**Comment by mgorny** [comment]
Hmm, it doesn't seem to be entirely correct:

```
app-crypt/aespipe
  ProbableUSE_EXPAND: USE_EXPAND group 'cpu_flags_x86' matches local USE flag: 'cpu_flags_x86_padlock'
```

It's fine to override descriptions for flags; it's not to add extra flags.

**Comment by radhermit** [comment]
Overrides are now ignored in https://github.com/pkgcore/pkgcheck/commit/f22e59498ecf2002e138cb9e43888138811fbbc9.
