### ISSUE TITLE
Check for binary files in repo

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#82]
Basically a replacement for this qa script:
https://gitweb.gentoo.org/proj/qa-scripts.git/tree/find-binary-files.sh

**Comment by radhermit** [comment]
For this we'll probably either want to depend on python-magic, vendor it, or write our own cython-based libmagic wrapper.

**Comment by mgorny** [comment]
Note that there's also `sys-apps/file[python]`.

Maybe we could get away with a cheap 'looks like binary stuff' check of our own?

**Comment by radhermit** [comment]
Yeah, I recall looking at the python bindings to file a while ago and preferring python-magic to them.

**Comment by mgorny** [comment]
Yeah, I guess depending on python-magic is fine too. After all, it's just pkgcheck with the extra dep.

**Comment by radhermit** [comment]
I implemented it using a cheaper method that appears to work in most standard cases, libmagic increased the run time too much in comparison and also would require keeping a list of mime types to skip as your script did.

**Comment by radhermit** [comment]
Note that pkgcheck now requires chardet though for the cheaper method.

**Comment by mgorny** [comment]
Technically speaking, I don't chardet is strictly necessary as I think we require all files to be UTF-8.

**Comment by radhermit** [comment]
We require all *ebuilds* to be UTF-8. Patches that patch non-UTF-8 files will probably break if forcibly re-encoded to UTF-8.
