### ISSUE TITLE
python-r1-specific checks

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#83]
There are some meta-checks that catch common issues in Python ebuilds. If pkgcheck included them, we might get people to actually fix them.

The existing report is at: https://qa-reports.gentoo.org/output/gpyutils/missing-meta.txt

The code is at: https://github.com/mgorny/gpyutils/blob/master/gpy-find-missing-meta

IIRC the checks include:
* checking for missing `PYTHON_COMPAT=()` in ebuild (e.g. when it's declared via eclass).
* for python-r1/python-single-r1:
  * checking for missing `PYTHON_REQUIRED_USE` in `REQUIRED_USE`,
  * checking for missing `PYTHON_DEPS` in `RDEPEND`.
* for python-any-r1:
  * checking for missing `PYTHON_DEPS` (or `python_gen_any_dep()`) in `DEPEND`,
  * and for the above wrongly present in `RDEPEND`.

In all cases, it determines what atoms should be present for specific eclass + PYTHON_COMPAT combination, and scans the variables for anything looking like them.

**Comment by radhermit** [comment]
Closing as I think this was fixed by merging https://github.com/pkgcore/pkgcheck/pull/84.
