### ISSUE TITLE
Check for RESTRICT="!test? ( test )"

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#89]
Since we no longer treat `IUSE=test` as full magic, it would be nice to have a check verifying that all ebuilds having it also have:

    RESTRICT="!test? ( test )"

or likewise. I think the reasonable way of verifying it would be to look for Conditional with '!test' condition that has at least one immediate child of 'test'.

**Comment by radhermit** [comment]
Done via https://github.com/pkgcore/pkgcheck/commit/a35f1ede037674ab4c7daf9fbc4b3e9eac137177.
