### ISSUE TITLE
Check for missing unpacker deps

### ISSUE THREAD

**Issue by mgorny** [pkgcore/pkgcheck#95]
We'd use a check for ebuilds using SRC_URI archives requiring non-`@system` unpackers, and missing them in BDEPEND (DEPEND). Ideally, we'd match USE conditionals between both vars but I suppose a plain 'if .zip is in any SRC_URI, then app-arch/unzip must be in any BDEPEND' would also work for us.

https://projects.gentoo.org/pms/7/pms.html#x1-13500012.3.15 for a quick list.

**Comment by radhermit** [comment]
Fixed with https://github.com/pkgcore/pkgcheck/pull/96.
