### ISSUE TITLE
check if cached profiles are deprecated on startup

### ISSUE THREAD

**Issue by radhermit** [pkgcore/pkgcheck#99]
Currently profile caching is an all or nothing operation so the profiles have to manually refreshed after the initial cache creation. It would be nice to determine which cached profiles need to be updated automatically.

We'll probably have to scan the mtimes for all dependent files of a profile and see if the newest mtime is different than one we'll store in the cached profile object.

**Comment by mgorny** [comment]
Don't forget to cover file addition/removal.
